size = { 2048, 2048 }
components = {
	test_hud {
		position = {1600, 0, 400, 400},
	},
	vers {},
	sc_controls {}, 
	achs1 {}, 
	clock24 {}, 
	mech_aneroid {}, 
	svs {}, 
	termo {}, 
	uvid_15fk {}, 
	mach_meters {}, 
	uap14 {}, 
	eup53 {}, 
	agr {}, 
	pkp {}, 
	pkp { 
		pitch_corr_hdl = globalPropertyf("tu154ce/gauges/ahz/pitch_corr_R"), 
		pkp_on = globalPropertyi("tu154ce/switchers/ovhd/pkp_right_on"), 
		pkp_fail = globalPropertyi("tu154ce/bkk/pkp_fail_right"), 
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"), 
		bus36_volt = globalPropertyf("tu154ce/elec/bus36_volt_right"), 
		res_pitch = globalPropertyf("tu154ce/gauges/ahz/pitch_R"), 
		pitch_int = globalPropertyf("tu154ce/gyro/ahz_pitch_int_R"), 
		res_roll = globalPropertyf("tu154ce/gauges/ahz/roll_R"), 
		res_roll_bkk = globalPropertyf("tu154ce/bkk/pkp_roll_right"), 
		ahz_flag = globalPropertyf("tu154ce/gauges/ahz/ahz_flag_R"), 
		course_plank = globalPropertyf("tu154ce/gauges/ahz/course_plank_R"), 
		gs_plank = globalPropertyf("tu154ce/gauges/ahz/gs_plank_R"), 
		dir_roll = globalPropertyf("tu154ce/gauges/ahz/dir_roll_R"), 
		dir_pitch = globalPropertyf("tu154ce/gauges/ahz/dir_pitch_R"), 
		dir_roll_flag = globalPropertyf("tu154ce/gauges/ahz/dir_roll_flag_R"), 
		dir_pitch_flag = globalPropertyf("tu154ce/gauges/ahz/dir_pitch_flag_R"), 
		absu_pnp_mode = globalPropertyi("tu154ce/absu/absu_pnp_mode_2"), 
		absu_at_dif = globalPropertyf("tu154ce/absu_at_dif_right"), 
		speed_plank = globalPropertyf("tu154ce/gauges/ahz/speed_plank_R"), 
		power_cc = globalPropertyf("tu154ce/bkk/pkp_right_power_cc"), 
		fail = globalPropertyi("sim/operation/failures/rel_cop_ahz"),
	},
	mgv {}, 
	bkk {}, 
	vbe_altimeter { 
		position = {733, 839, 424, 424},
	},
	vbe_altimeter { 
		position = {1166, 839, 424, 424},
		gauge_num = 1,
		static_fail = globalPropertyi("sim/operation/failures/rel_static2"),
		pressure = globalPropertyf("tu154ce/gauges/alt/vbe_press_right"),  
		brt_knob = globalPropertyf("tu154ce/gauges/alt/vbe_brt_right"),  
		press_knob = globalPropertyi("tu154ce/gauges/alt/vbe_press_knob_right"),  
		fl_knob = globalPropertyi("tu154ce/gauges/alt/vbe_fl_knob_right"),  
		mode_button = globalPropertyi("tu154ce/gauges/alt/vbe_mode_but_right"),  
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"), 
		bus115_volt = globalPropertyf("tu154ce/elec/bus115_3_volt"), 
		vbe_on = globalPropertyi("tu154ce/switchers/ovhd/vbe_2_on"),  
		vbe_mode = globalPropertyi("tu154ce/gauges/alt/vbe_mode_right"),  
		vbe_std = globalPropertyi("tu154ce/gauges/alt/vbe_std_right"),  
		alt_mtr = globalPropertyf("tu154ce/gauges/alt/vbe_alt_right"),  
		vbe_flightlevel = globalPropertyi("tu154ce/gauges/alt/vbe_flightlevel_right"),  
		fail = globalPropertyi("sim/operation/failures/rel_cop_alt"), 
	},
	rv5 {},
	rv5 {
		altitude = globalPropertyf("sim/cockpit2/gauges/indicators/radio_altimeter_height_ft_copilot"),  
		dh_set = globalPropertyf("tu154ce/gauges/alt/radioalt_dh_right"),  
		test_btn = globalPropertyf("tu154ce/gauges/alt/radioalt_button_right"),  
		rv_on = globalPropertyf("tu154ce/switchers/ovhd/rv5_2_on"),  
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"),
		bus115_volt = globalPropertyf("tu154ce/elec/bus115_3_volt"),
		rv_angle = globalPropertyf("tu154ce/gauges/alt/radioalt_needle_right"),  
		rv_flag = globalPropertyi("tu154ce/gauges/alt/radioalt_flag_right"),  
		rv_lamp = globalPropertyf("tu154ce/lights/small/rv5_right_dh"),  
		rv5_dh_signal = globalPropertyi("tu154ce/misc/rv5_dh_signal_right"),
		rv_сс = globalPropertyf("tu154ce/elec/rv5_right_cc"),  
		rv5_alt = globalPropertyf("tu154ce/misc/rv5_alt_right"),  
		rv_fail = globalPropertyi("tu154ce/failures/rv2_fail"),  
	},
	msrp_clock { 
		position = {12, 762, 195, 84},
	},
	door_panel {}, 
	tcas {
		position = {0, 0, 2048, 2048},
	},
	taws {
		position = {1034, 1270, 1000, 770},
	},
	tks {},
	pnp {}, 
	pnp { 
		gauge_num = 1, 
		course_ga = globalPropertyf("tu154ce/tks/course_ga_2"), 
		course_bgmk = globalPropertyf("tu154ce/tks/course_bgmk_2"), 
		gyro_fail = globalPropertyi("tu154ce/tks/fail_right"), 
		obs = globalPropertyf("tu154ce/gauges/compas/pkp_obs_set_R"),  
		obs_side = globalPropertyf("tu154ce/gauges/compas/pkp_obs_set_L"),  
		pnp_mode = globalPropertyi("tu154ce/switchers/ovhd/curs_pnp_mode_2"), 
		pkp_obs_knob = globalPropertyf("tu154ce/gauges/compas/pkp_obs_knob_R"), 
		pkp_gyro_course = globalPropertyf("tu154ce/gauges/compas/pkp_gyro_course_R"), 
		pkp_obs = globalPropertyf("tu154ce/gauges/compas/pkp_obs_R"), 
		pkp_helper_course = globalPropertyf("tu154ce/gauges/compas/pkp_helper_course_R"), 
		pkp_slip_angle = globalPropertyf("tu154ce/gauges/compas/pkp_slip_angle_R"), 
		pkp_course_plank = globalPropertyf("tu154ce/gauges/compas/pkp_course_plank_R"), 
		pkp_gs_plank = globalPropertyf("tu154ce/gauges/compas/pkp_gs_plank_R"), 
		pkp_gs_flag = globalPropertyi("tu154ce/gauges/compas/pkp_gs_flag_R"), 
		pkp_course_flag = globalPropertyi("tu154ce/gauges/compas/pkp_course_flag_R"), 
		pkp_main_flag = globalPropertyi("tu154ce/gauges/compas/pkp_main_flag_R"), 
		pkp_obs_flag = globalPropertyi("tu154ce/gauges/compas/pkp_obs_flag_R"), 
		pkp_obs_one = globalPropertyf("tu154ce/gauges/compas/pkp_obs_one_R"), 
		pkp_obs_ten = globalPropertyf("tu154ce/gauges/compas/pkp_obs_ten_R"), 
		pkp_obs_hundr = globalPropertyf("tu154ce/gauges/compas/pkp_obs_hundr_R"), 
		absu_pnp_mode = globalPropertyi("tu154ce/absu/absu_pnp_mode_2"), 
		absu_pnp_mode_2 = globalPropertyi("tu154ce/absu/absu_pnp_mode_1"), 
		pnp_sp_lamp = globalPropertyf("tu154ce/lights/small/pnp_sp_right"), 
		pnp_vor_lamp = globalPropertyf("tu154ce/lights/small/pnp_vor_right"), 
		pnp_nv_lamp = globalPropertyf("tu154ce/lights/small/pnp_nv_right"), 
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_left"),
		bus36_volt = globalPropertyf("tu154ce/elec/bus36_volt_right"),
		fail_ga = globalPropertyf("sim/operation/failures/rel_cop_dgy"),
		tks_on = globalPropertyi("tu154ce/switchers/ovhd/tks_on_2"), 
	}, 
	rmi {}, 
	rmi {
		course_bgmk = globalPropertyf("tu154ce/tks/course_bgmk_1"), 
		bus36_volt = globalPropertyf("tu154ce/elec/bus36_volt_pts250_2"), 
		radiocomp_scale = globalPropertyf("tu154ce/gauges/compas/radiocomp_scale_right"), 
		bearing_1 = globalPropertyf("tu154ce/gauges/compas/bearing_1_right"), 
		bearing_2 = globalPropertyf("tu154ce/gauges/compas/bearing_2_right"), 
		source_1_switch = globalPropertyi("tu154ce/gauges/compas/source_1_switch_right"), 
		source_2_switch = globalPropertyi("tu154ce/gauges/compas/source_2_switch_right"), 
	},
	diss {}, 
	usvp {}, 
	rsbn {}, 
	radio { 
		position = {0, 0, 2048, 2048},
	},
	nvu {}, 
	absu {}, 
	misc_lamps {}, 
	radar {
		position = {0, 0, 2048, 2048},
	},
	vent {},
	water_panel {},
	gns430 {},
	misc_fails {},
}