defineProperty("bus27_volt_left", globalPropertyf("sim/custom/elec/bus27_volt_left")) 
defineProperty("bus27_volt_right", globalPropertyf("sim/custom/elec/bus27_volt_right")) 
defineProperty("msrp_recording", globalPropertyi("sim/custom/msrp/msrp_recording")) 
defineProperty("msrp_date_ten", globalPropertyf("sim/custom/switchers/eng/msrp_date_ten")) 
defineProperty("msrp_date_one", globalPropertyf("sim/custom/switchers/eng/msrp_date_one")) 
defineProperty("msrp_month_ten", globalPropertyf("sim/custom/switchers/eng/msrp_month_ten")) 
defineProperty("msrp_month_one", globalPropertyf("sim/custom/switchers/eng/msrp_month_one")) 
defineProperty("msrp_year_ten", globalPropertyf("sim/custom/switchers/eng/msrp_year_ten")) 
defineProperty("msrp_year_one", globalPropertyf("sim/custom/switchers/eng/msrp_year_one")) 
defineProperty("msrp_route_hun", globalPropertyf("sim/custom/switchers/eng/msrp_route_hun")) 
defineProperty("msrp_route_ten", globalPropertyf("sim/custom/switchers/eng/msrp_route_ten")) 
defineProperty("msrp_route_one", globalPropertyf("sim/custom/switchers/eng/msrp_route_one")) 
defineProperty("msrp_mlp_1", globalPropertyf("sim/custom/switchers/eng/msrp_mlp_1")) 
defineProperty("msrp_mlp_2", globalPropertyf("sim/custom/switchers/eng/msrp_mlp_2")) 
defineProperty("msrp_night_day", globalPropertyf("sim/custom/switchers/eng/msrp_night_day")) 
defineProperty("msrp_main_switch", globalPropertyf("sim/custom/switchers/eng/msrp_main_switch")) 
defineProperty("total_flight_time_sec", globalPropertyf("sim/time/total_flight_time_sec"))
defineProperty("zulu_time_hours", globalPropertyf("sim/cockpit2/clock_timer/zulu_time_hours"))
defineProperty("zulu_time_minutes", globalPropertyf("sim/cockpit2/clock_timer/zulu_time_minutes"))
defineProperty("zulu_time_seconds", globalPropertyf("sim/cockpit2/clock_timer/zulu_time_seconds"))
defineProperty("latitude", globalPropertyf("sim/flightmodel/position/latitude")) 
defineProperty("longitude", globalPropertyf("sim/flightmodel/position/longitude")) 
defineProperty("true_crs", globalPropertyf("sim/flightmodel/position/true_psi")) 
defineProperty("MSL", globalPropertyf("sim/flightmodel/position/elevation")) 
defineProperty("mgv_pitch", globalPropertyf("sim/custom/gyro/mgv_contr_pitch")) 
defineProperty("mgv_roll", globalPropertyf("sim/custom/gyro/mgv_contr_roll")) 
defineProperty("sideslip_degrees", globalPropertyf("sim/cockpit2/gauges/indicators/sideslip_degrees"))
defineProperty("yoke_pitch", globalPropertyf("sim/custom/controlls/yoke_pitch")) 
defineProperty("yoke_roll", globalPropertyf("sim/custom/controlls/yoke_roll")) 
defineProperty("pedals_turn", globalPropertyf("sim/custom/controlls/pedals")) 
defineProperty("int_pitch_trim", globalPropertyf("sim/custom/trimmers/int_pitch_trim")) 
defineProperty("int_roll_trim", globalPropertyf("sim/custom/trimmers/int_roll_trim")) 
defineProperty("int_yaw_trim", globalPropertyf("sim/custom/trimmers/int_yaw_trim")) 
defineProperty("stab_ind", globalPropertyf("sim/custom/gauges/misc/stab_ind")) 
defineProperty("flap_left_ind", globalPropertyf("sim/custom/gauges/misc/flap_left_ind")) 
defineProperty("flap_right_ind", globalPropertyf("sim/custom/gauges/misc/flap_right_ind")) 
defineProperty("slats", globalPropertyf("sim/flightmodel2/controls/slat1_deploy_ratio")) 
defineProperty("ail_L", globalPropertyf("sim/flightmodel/controls/wing3l_ail1def")) 
defineProperty("ail_R", globalPropertyf("sim/flightmodel/controls/wing3r_ail1def")) 
defineProperty("elevator_L", globalPropertyf("sim/flightmodel/controls/hstab1_elv1def")) 
defineProperty("elevator_R", globalPropertyf("sim/flightmodel/controls/hstab2_elv1def")) 
defineProperty("rudder", globalPropertyf("sim/flightmodel/controls/vstab2_rud1def")) 
defineProperty("spd_brk_inn_L", globalPropertyf("sim/flightmodel/controls/wing1l_spo1def")) 
defineProperty("spd_brk_inn_R", globalPropertyf("sim/flightmodel/controls/wing1r_spo1def")) 
defineProperty("spd_brk_mid_L", globalPropertyf("sim/flightmodel/controls/wing2l_spo2def")) 
defineProperty("spd_brk_mid_R", globalPropertyf("sim/flightmodel/controls/wing2r_spo2def")) 
defineProperty("roll_spoil_L", globalPropertyf("sim/flightmodel/controls/wing2l_spo1def")) 
defineProperty("roll_spoil_R", globalPropertyf("sim/flightmodel/controls/wing2r_spo1def")) 
defineProperty("msl_alt", globalPropertyf("sim/flightmodel/position/elevation"))  
defineProperty("msl_press", globalPropertyf("sim/weather/barometer_sealevel_inhg"))  
defineProperty("rv5_alt", globalPropertyf("sim/custom/misc/rv5_alt_left"))  
defineProperty("vvi", globalPropertyf("sim/cockpit2/gauges/indicators/vvi_fpm_pilot")) 
defineProperty("aoa_ind", globalPropertyf("sim/custom/gauges/misc/aoa_ind")) 
defineProperty("gforce_ind", globalPropertyf("sim/custom/gauges/misc/gforce_ind")) 
defineProperty("ias", globalPropertyf("sim/cockpit2/gauges/indicators/airspeed_kts_pilot"))
defineProperty("mach_svs", globalPropertyf("sim/custom/svs/machno")) 
defineProperty("course_gpk", globalPropertyf("sim/custom/tks/course_gpk")) 
defineProperty("course_gmk", globalPropertyf("sim/custom/tks/course_gmk")) 
defineProperty("rpm_high_1", globalPropertyf("sim/custom/gauges/engine/rpm_high_1")) 
defineProperty("rpm_high_2", globalPropertyf("sim/custom/gauges/engine/rpm_high_2")) 
defineProperty("rpm_high_3", globalPropertyf("sim/custom/gauges/engine/rpm_high_3")) 
defineProperty("ENGN_propmode_1", globalPropertyf("sim/flightmodel/engine/ENGN_propmode[0]"))
defineProperty("ENGN_propmode_2", globalPropertyf("sim/flightmodel/engine/ENGN_propmode[1]"))
defineProperty("ENGN_propmode_3", globalPropertyf("sim/flightmodel/engine/ENGN_propmode[2]"))
defineProperty("fuel_flow_1", globalPropertyf("sim/custom/gauges/eng/fuel_flow_1")) 
defineProperty("fuel_flow_2", globalPropertyf("sim/custom/gauges/eng/fuel_flow_2")) 
defineProperty("fuel_flow_3", globalPropertyf("sim/custom/gauges/eng/fuel_flow_3")) 
defineProperty("m_total", globalPropertyf("sim/flightmodel/weight/m_total")) 
defineProperty("m_fuel", globalPropertyf("sim/flightmodel/weight/m_fuel_total")) 
defineProperty("cg_pos_actual", globalPropertyf("sim/custom/misc/cg_pos_actual")) 
defineProperty("deflection_mtr_3", globalPropertyf("sim/flightmodel2/gear/tire_vertical_deflection_mtr[2]")) 
defineProperty("roll_main_mode", globalPropertyi("sim/custom/absu/roll_main_mode")) 
defineProperty("pitch_main_mode", globalPropertyi("sim/custom/absu/pitch_main_mode")) 
defineProperty("stu_mode", globalPropertyi("sim/custom/absu/stu_mode")) 
defineProperty("deploy_ratio_1", globalPropertyf("sim/flightmodel2/gear/deploy_ratio[0]")) 
defineProperty("deploy_ratio_2", globalPropertyf("sim/flightmodel2/gear/deploy_ratio[1]")) 
defineProperty("deploy_ratio_3", globalPropertyf("sim/flightmodel2/gear/deploy_ratio[2]")) 
defineProperty("outer_marker", globalPropertyi("sim/cockpit/misc/outer_marker_lit"))   
defineProperty("middle_marker", globalPropertyi("sim/cockpit/misc/middle_marker_lit"))
defineProperty("inner_marker", globalPropertyi("sim/cockpit/misc/inner_marker_lit"))
defineProperty("nav_cs_flag", globalPropertyi("sim/custom/radio/nav1_cs_flag"))
defineProperty("nav_gs_flag", globalPropertyi("sim/custom/radio/nav1_gs_flag"))
defineProperty("nav_cs", globalPropertyf("sim/custom/radio/nav1_cs"))
defineProperty("nav_gs", globalPropertyf("sim/custom/radio/nav1_gs"))
defineProperty("wind_direction_degt", globalPropertyf("sim/weather/wind_direction_degt"))
defineProperty("wind_speed_kt", globalPropertyf("sim/weather/wind_speed_kt"))
defineProperty("msrp_27_L_cc", globalPropertyf("sim/custom/msrp/msrp_27_L_cc")) 
defineProperty("msrp_27_R_cc", globalPropertyf("sim/custom/msrp/msrp_27_R_cc")) 
defineProperty("msrp_power", globalPropertyi("sim/custom/msrp/msrp_power"))  
defineProperty("frame_time", globalPropertyf("sim/custom/time/frame_time")) 
local filename = panelDir.."/black_box/default_file.bbox" 
local panel_numbers = "0"
local function createFileName()
	local date_ten = get(msrp_date_ten)
	local date_one = get(msrp_date_one)
	local month_ten = get(msrp_month_ten)
	local month_one = get(msrp_month_one)
	local year_ten = get(msrp_year_ten)
	local year_one = get(msrp_year_one)
	local route_hun = get(msrp_route_hun)
	local route_ten = get(msrp_route_ten)
	local route_one = get(msrp_route_one)
	panel_numbers = date_ten .. date_one .."_".. month_ten .. month_one .."_".. year_ten .. year_one .."_".. route_hun .. route_ten .. route_one
	filename = panelDir.."/black_box/".. panel_numbers .. ".bbox"
end
createFileName()
function create_file()
	local savefile = io.open(filename, "r")
	if savefile then 
		savefile:close()
		return true
	else
		savefile = io.open(filename, "w") 
	end
	if savefile then
		savefile:write("0\t"..panel_numbers.."\n") 
		savefile:write("1\t") 
			savefile:write("Sim time\t") 
			savefile:write("Time stamp\t") 
			savefile:write("Latitude\t") 
			savefile:write("Longtitude\t") 
			savefile:write("TrueCRS\t") 
			savefile:write("MSL alt\t") 
			savefile:write("Pitch\t") 
			savefile:write("Roll\t") 
			savefile:write("Slip\t") 
			savefile:write("Yoke pitch\t") 
			savefile:write("Yoke roll\t") 
			savefile:write("Yoke yaw\t") 
			savefile:write("Trim pitch\t") 
			savefile:write("Trim roll\t") 
			savefile:write("Trim yaw\t") 
			savefile:write("Stab pos\t") 
			savefile:write("Flaps L\t") 
			savefile:write("Flaps R\t") 
			savefile:write("Slats\t") 
			savefile:write("Aileron L\t") 
			savefile:write("Aileron R\t") 
			savefile:write("Elevator L\t") 
			savefile:write("Elevator R\t") 
			savefile:write("Rudder\t") 
			savefile:write("Spoiler OUT L\t") 
			savefile:write("Spoiler MID L\t") 
			savefile:write("Spoiler INN L\t") 
			savefile:write("Spoiler OUT R\t") 
			savefile:write("Spoiler MID R\t") 
			savefile:write("Spoiler INN R\t") 
			savefile:write("Baro alt\t") 
			savefile:write("Radio alt\t") 
			savefile:write("Vertical spd\t") 
			savefile:write("AoA\t") 
			savefile:write("G-load\t") 
			savefile:write("Airspeed\t") 
			savefile:write("Mach No\t") 
			savefile:write("Mag CRS\t") 
			savefile:write("TKS CRS\t") 
			savefile:write("ILS CRS\t") 
			savefile:write("ILS GS\t") 
			savefile:write("CRS Flag\t") 
			savefile:write("GS Flag\t") 
			savefile:write("Wind dir\t") 
			savefile:write("Wind speed\t") 
			savefile:write("ENG 1 RPM\t") 
			savefile:write("ENG 2 RPM\t") 
			savefile:write("ENG 3 RPM\t") 
			savefile:write("ENG 1 FF\t") 
			savefile:write("ENG 2 FF\t") 
			savefile:write("ENG 3 FF\t") 
			savefile:write("Total weight\t") 
			savefile:write("Total CG\t") 
			savefile:write("Total fuel\t") 
			savefile:write("On Ground\t") 
			savefile:write("Gear Down\t") 
			savefile:write("ABSU Roll mode\t") 
			savefile:write("ABSU Pitch mode\t") 
			savefile:write("ABSU AT mode\t") 
			savefile:write("Marker\t") 
			savefile:write("\n") 
		savefile:write("2\t") 
			savefile:write("sec\t") 
			savefile:write("HH:MM:SS\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("m\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("ratio\t") 
			savefile:write("m\t") 
			savefile:write("m\t") 
			savefile:write("m/s\t") 
			savefile:write("deg\t") 
			savefile:write("g\t") 
			savefile:write("km/h\t") 
			savefile:write("M\t") 
			savefile:write("deg\t") 
			savefile:write("deg\t") 
			savefile:write("dot\t") 
			savefile:write("dot\t") 
			savefile:write("bool\t") 
			savefile:write("bool\t") 
			savefile:write("deg\t") 
			savefile:write("km/h\t") 
			savefile:write("%\t") 
			savefile:write("%\t") 
			savefile:write("%\t") 
			savefile:write("kg/h\t") 
			savefile:write("kg/h\t") 
			savefile:write("kg/h\t") 
			savefile:write("kg\t") 
			savefile:write("%MAC\t") 
			savefile:write("kg\t") 
			savefile:write("bool\t") 
			savefile:write("bool\t") 
			savefile:write("mode\t") 
			savefile:write("mode\t") 
			savefile:write("mode\t") 
			savefile:write("mode\t") 
			savefile:write("\n") 
		savefile:write("3\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("-10/20\t") 
			savefile:write("-30/30\t") 
			savefile:write("-20/20\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("0/-5.5\t") 
			savefile:write("0/45\t") 
			savefile:write("0/45\t") 
			savefile:write("0/22\t") 
			savefile:write("-20/20\t") 
			savefile:write("-20/20\t") 
			savefile:write("-20/25\t") 
			savefile:write("-20/25\t") 
			savefile:write("-25/25\t") 
			savefile:write("0/1\t") 
			savefile:write("0/1\t") 
			savefile:write("0/1\t") 
			savefile:write("0/1\t") 
			savefile:write("0/1\t") 
			savefile:write("0/1\t") 
			savefile:write("0/0\t") 
			savefile:write("0/900\t") 
			savefile:write("-30/30\t") 
			savefile:write("-5/12\t") 
			savefile:write("-0.5/2.5\t") 
			savefile:write("-100/600\t") 
			savefile:write("-0.2/0.86\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("-1/1\t") 
			savefile:write("-1/1\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("40/96\t") 
			savefile:write("40/96\t") 
			savefile:write("40/96\t") 
			savefile:write("400/5300\t") 
			savefile:write("400/5300\t") 
			savefile:write("400/5300\t") 
			savefile:write("54000/100000\t") 
			savefile:write("18/32\t") 
			savefile:write("2500/40000\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("0/0\t") 
			savefile:write("\n") 
		savefile:write("4\t") 
			savefile:write("time\t") 
			savefile:write("time\t") 
			savefile:write("coordinates\t") 
			savefile:write("coordinates\t") 
			savefile:write("course\t") 
			savefile:write("MSL\t") 
			savefile:write("orientation\t") 
			savefile:write("orientation\t") 
			savefile:write("orientation\t") 
			savefile:write("yoke\t") 
			savefile:write("yoke\t") 
			savefile:write("yoke\t") 
			savefile:write("trim\t") 
			savefile:write("trim\t") 
			savefile:write("trim\t") 
			savefile:write("stab\t") 
			savefile:write("wing mech\t") 
			savefile:write("wing mech\t") 
			savefile:write("wing mech\t") 
			savefile:write("controls\t") 
			savefile:write("controls\t") 
			savefile:write("controls\t") 
			savefile:write("controls\t") 
			savefile:write("controls\t") 
			savefile:write("spoilers\t") 
			savefile:write("spoilers\t") 
			savefile:write("spoilers\t") 
			savefile:write("spoilers\t") 
			savefile:write("spoilers\t") 
			savefile:write("spoilers\t") 
			savefile:write("altitude\t") 
			savefile:write("altitude\t") 
			savefile:write("vertical speed\t") 
			savefile:write("aoa\t") 
			savefile:write("G-load\t") 
			savefile:write("airspeed\t") 
			savefile:write("mach\t") 
			savefile:write("course\t") 
			savefile:write("course\t") 
			savefile:write("ILS\t") 
			savefile:write("ILS\t") 
			savefile:write("ILS\t") 
			savefile:write("ILS\t") 
			savefile:write("course\t") 
			savefile:write("wind speed\t") 
			savefile:write("engine RPM\t") 
			savefile:write("engine RPM\t") 
			savefile:write("engine RPM\t") 
			savefile:write("fuel flow\t") 
			savefile:write("fuel flow\t") 
			savefile:write("fuel flow\t") 
			savefile:write("mass\t") 
			savefile:write("CG\t") 
			savefile:write("mass\t") 
			savefile:write("event\t") 
			savefile:write("event\t") 
			savefile:write("event\t") 
			savefile:write("event\t") 
			savefile:write("event\t") 
			savefile:write("event\t") 
			savefile:write("\n") 
		savefile:close()
		return true
	else
		print("error saving file. check if there is \"black_box\" folder here: "..panelDir.. " and permissions for it")
		return false
	end
end
function write_file() 
	local savefile = io.open(filename, "a")
	if savefile then
		savefile:write("9\t") 
			savefile:write(math.floor(get(total_flight_time_sec)*100)*0.01, "\t") 
			local ZULU = get(zulu_time_hours)..":"..get(zulu_time_minutes)..":"..get(zulu_time_seconds)
			savefile:write(ZULU.."\t") 
			savefile:write(math.floor(get(latitude)*1000000)*0.000001, "\t") 
			savefile:write(math.floor(get(longitude)*1000000)*0.000001, "\t") 
			savefile:write(math.floor(get(true_crs)*100)*0.01, "\t") 
			savefile:write(math.floor(get(MSL)*100)*0.01, "\t") 
			local pitch = get(mgv_pitch)
			if pitch > 0 then pitch = math.floor(pitch*100)*0.01
			elseif pitch < 0 then pitch = math.ceil(pitch*100)*0.01 end
			savefile:write(pitch, "\t")
			local roll = get(mgv_roll)
			if roll > 0 then roll = math.floor(roll*100)*0.01
			elseif roll < 0 then roll = math.ceil(roll*100)*0.01 end
			savefile:write(roll, "\t") 
			local slip = get(sideslip_degrees)
			if slip > 0 then slip = math.floor(slip*100)*0.01
			elseif slip < 0 then slip = math.ceil(slip*100)*0.01 end
			savefile:write(slip, "\t") 
			local Y_pitch = get(yoke_pitch)
			if Y_pitch > 0 then Y_pitch = math.floor(Y_pitch*100)*0.01
			elseif Y_pitch < 0 then Y_pitch = math.ceil(Y_pitch*100)*0.01 end
			savefile:write(Y_pitch, "\t") 
			local Y_roll = get(yoke_roll)
			if Y_roll > 0 then Y_roll = math.floor(Y_roll*100)*0.01
			elseif Y_roll < 0 then Y_roll = math.ceil(Y_roll*100)*0.01 end
			savefile:write(Y_roll, "\t")
			local Y_yaw = get(pedals_turn)
			if Y_yaw > 0 then Y_yaw = math.floor(Y_yaw*100)*0.01
			elseif Y_yaw < 0 then Y_yaw = math.ceil(Y_yaw*100)*0.01 end
			savefile:write(Y_yaw, "\t")
			local T_pitch = get(int_pitch_trim)
			if T_pitch > 0 then T_pitch = math.floor(T_pitch*100)*0.01
			elseif T_pitch < 0 then T_pitch = math.ceil(T_pitch*100)*0.01 end
			savefile:write(T_pitch, "\t")
			local T_roll = get(int_roll_trim)
			if T_roll > 0 then T_roll = math.floor(T_roll*100)*0.01
			elseif T_roll < 0 then T_roll = math.ceil(T_roll*100)*0.01 end
			savefile:write(T_roll, "\t")
			local T_yaw = get(int_yaw_trim)
			if T_yaw > 0 then T_yaw = math.floor(T_yaw*100)*0.01
			elseif T_yaw < 0 then T_yaw = math.ceil(T_yaw*100)*0.01 end
			savefile:write(T_yaw, "\t")
			savefile:write(math.floor(get(stab_ind)*100)*0.01 .."\t") 
			savefile:write(math.floor(get(flap_left_ind)*100)*0.01 .."\t") 
			savefile:write(math.floor(get(flap_right_ind)*100)*0.01 .."\t")
			savefile:write(math.floor(get(slats)*100)*0.22 .."\t")
			local AIL_L = get(ail_L)
			if AIL_L > 0 then AIL_L = math.floor(AIL_L*100)*0.01
			elseif AIL_L < 0 then AIL_L = math.ceil(AIL_L*100)*0.01 end
			savefile:write(AIL_L, "\t")
			local AIL_R = get(ail_R)
			if AIL_R > 0 then AIL_R = math.floor(AIL_R*100)*0.01
			elseif AIL_R < 0 then AIL_R = math.ceil(AIL_R*100)*0.01 end
			savefile:write(AIL_R, "\t")
			local ELEV_L = -get(elevator_L)
			if ELEV_L > 0 then ELEV_L = math.floor(ELEV_L*100)*0.01
			elseif ELEV_L < 0 then ELEV_L = math.ceil(ELEV_L*100)*0.01 end
			savefile:write(ELEV_L, "\t")
			local ELEV_R = -get(elevator_R)
			if ELEV_R > 0 then ELEV_R = math.floor(ELEV_R*100)*0.01
			elseif ELEV_R < 0 then ELEV_R = math.ceil(ELEV_R*100)*0.01 end
			savefile:write(ELEV_R, "\t")
			local RUDD = get(rudder)
			if RUDD > 0 then RUDD = math.floor(RUDD*100)*0.01
			elseif RUDD < 0 then RUDD = math.ceil(RUDD*100)*0.01 end
			savefile:write(RUDD, "\t")
			savefile:write(math.floor(get(roll_spoil_L)*100/20)*0.01 .."\t") 
			savefile:write(math.floor(get(spd_brk_mid_L)*100/45)*0.01 .."\t") 
			savefile:write(math.floor(get(spd_brk_inn_L)*100/50)*0.01 .."\t") 
			savefile:write(math.floor(get(roll_spoil_R)*100/20)*0.01 .."\t") 
			savefile:write(math.floor(get(spd_brk_mid_R)*100/45)*0.01 .."\t") 
			savefile:write(math.floor(get(spd_brk_inn_R)*100/50)*0.01 .."\t") 
			local baro_alt = get(msl_alt) + (29.92 - get(msl_press)) * 1000 * 0.3048  
			if baro_alt > 0 then baro_alt = math.floor(baro_alt*10)*0.1
			elseif baro_alt < 0 then baro_alt = math.ceil(baro_alt*10)*0.1 end
			savefile:write(baro_alt, "\t") 
			savefile:write(math.floor(get(rv5_alt)*10)*0.1, "\t") 
			savefile:write(math.floor(get(vvi)*0.00508*100)*0.01, "\t")
			savefile:write(math.floor(get(aoa_ind)*100)*0.01, "\t") 
			savefile:write(math.floor(get(gforce_ind)*100)*0.01, "\t") 
			savefile:write(math.floor(get(ias)*1.852*10)*0.1, "\t") 
			savefile:write(math.floor(get(mach_svs)*10000)*0.0001, "\t")
			savefile:write(math.floor(get(course_gmk)*100)*0.01, "\t")
			savefile:write(math.floor(get(course_gpk)*100)*0.01, "\t")
			savefile:write(math.floor(get(nav_cs)*100*2.5)*0.01, "\t")
			savefile:write(math.floor(get(nav_gs)*100*2.5)*0.01, "\t")
			savefile:write(get(nav_cs_flag), "\t")
			savefile:write(get(nav_gs_flag), "\t")
			savefile:write(math.floor(get(wind_direction_degt)*100)*0.01, "\t")
			savefile:write(math.floor(get(wind_speed_kt)*1.852*100)*0.01, "\t")
			savefile:write(math.floor(get(rpm_high_1)*100)*0.01 * (1 - 2*bool2int(get(ENGN_propmode_1) == 3)), "\t")
			savefile:write(math.floor(get(rpm_high_2)*100)*0.01 * (1 - 2*bool2int(get(ENGN_propmode_2) == 3)), "\t")
			savefile:write(math.floor(get(rpm_high_3)*100)*0.01 * (1 - 2*bool2int(get(ENGN_propmode_3) == 3)), "\t")
			savefile:write(math.floor(get(fuel_flow_1)*100)*0.01, "\t")
			savefile:write(math.floor(get(fuel_flow_2)*100)*0.01, "\t")
			savefile:write(math.floor(get(fuel_flow_3)*100)*0.01, "\t")
			savefile:write(math.floor(get(m_total)), "\t")
			savefile:write(math.floor(get(cg_pos_actual)*100)*0.01, "\t")
			savefile:write(math.floor(get(m_fuel)), "\t")
			savefile:write(bool2int(get(deflection_mtr_3) > 0.01), "\t")
			local gear = bool2int(get(deploy_ratio_1) > 0.99 and get(deploy_ratio_2) > 0.99 and get(deploy_ratio_3) > 0.99)
			savefile:write(gear, "\t")
			savefile:write(get(roll_main_mode), "\t")
			savefile:write(get(pitch_main_mode), "\t")
			savefile:write(get(stu_mode), "\t")
			local mark = 0
			if get(inner_marker) == 1 then mark = 1
			elseif get(middle_marker) == 1 then mark = 2
			elseif get(outer_marker) == 1 then mark = 3
			end
			savefile:write(mark.."\t")
			savefile:write("\n") 
		savefile:close()
		return true
	else
		print("cannot write into file")
		return false
	end
end
local save_timer = 0
function update()
	local passed = get(frame_time)
	local airspeed = get(ias) * 1.852
	local power27_L = get(bus27_volt_left) > 13
	local power27_R = get(bus27_volt_right) > 13
	save_timer = save_timer + passed
	local power = (power27_L or power27_R) and get(msrp_main_switch) == 1
	if save_timer > 1 then
		save_timer = 0
		if airspeed > 80 and (get(msrp_mlp_1) == 1 or get(msrp_mlp_2) == 1) and power then
			create_file()
			write_file()
			set(msrp_recording, 1)
		else
			createFileName()
			set(msrp_recording, 0)
		end
	end
	if power then
		if power27_R then
			set(msrp_27_L_cc, 0)
			set(msrp_27_R_cc, 5)
		elseif power27_L then
			set(msrp_27_L_cc, 5)
			set(msrp_27_R_cc, 0)
		end
	else
		set(msrp_27_L_cc, 0)
		set(msrp_27_R_cc, 0)
	end
	set(msrp_power, bool2int(power))
end
