size = {2048, 2048}
components = {
	vhf {
		position = {13, 658, 420, 93},
	},
	vhf {
		position = {13, 556, 420, 93},
		num = 1,
		vhf_left = globalPropertyi("tu154ce/rotary/ovhd/vhf_2_left"),  
		vhf_right = globalPropertyi("tu154ce/rotary/ovhd/vhf_2_right"),  
		vhf_on = globalPropertyi("tu154ce/switchers/ovhd/vhf_2_on"),  
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"), 
		com_power = globalPropertyi("sim/cockpit2/radios/actuators/com2_power"), 
		vhf_cc = globalPropertyf("tu154ce/radio/vhf2_cc"),
	},
	course_mp {
		position = {288, 914, 410, 108},
	},
	course_mp {
		position = {288, 797, 410, 108},
		frequency = globalPropertyf("sim/cockpit2/radios/actuators/nav2_frequency_hz"),  
		v_plank = globalPropertyf("sim/cockpit2/radios/indicators/nav2_hdef_dots_pilot"), 
		h_plank = globalPropertyf("sim/cockpit2/radios/indicators/nav2_vdef_dots_pilot"), 
		cr_flag = globalPropertyf("sim/cockpit2/radios/indicators/nav2_flag_from_to_pilot"), 
		gs_flag = globalPropertyf("sim/cockpit/radios/nav2_CDI"),  
		nav_deg = globalPropertyf("sim/cockpit2/radios/indicators/nav2_relative_bearing_deg"), 
		sim_fail = globalPropertyi("sim/operation/failures/rel_nav2"), 
		distance = globalPropertyf("sim/cockpit2/radios/indicators/nav2_dme_distance_nm"),  
		obs = globalPropertyi("sim/cockpit2/radios/actuators/nav2_obs_deg_mag_pilot"), 
		nav_fail = globalPropertyi("tu154ce/failures/nav2_fail"), 
		dme_fail = globalPropertyi("tu154ce/failures/dme2_fail"), 
		sd75_on = globalPropertyi("tu154ce/switchers/ovhd/sd75_2_on"), 
		curs_np_on = globalPropertyi("tu154ce/switchers/ovhd/curs_np_on_2"), 
		bus36_volt = globalPropertyf("tu154ce/elec/bus36_volt_right"),
		bus115_volt = globalPropertyf("tu154ce/elec/bus115_3_volt"),
		nav_pow_cc = globalPropertyf("tu154ce/radio/nav2_pow_cc"), 
		nav_mode = globalPropertyi("tu154ce/switchers/nav_2_mode"), 
		nav_man_auto = globalPropertyi("tu154ce/switchers/nav_2_man_auto"), 
		nav_mile_km = globalPropertyi("tu154ce/switchers/nav_2_mile_km"), 
		nav_left = globalPropertyi("tu154ce/rotary/ovhd/nav_2_left"), 
		nav_right = globalPropertyi("tu154ce/rotary/ovhd/nav_2_right"), 
		nav_but_1 = globalPropertyi("tu154ce/buttons/ovhd/nav_2_but_1"), 
		nav_but_2 = globalPropertyi("tu154ce/buttons/ovhd/nav_2_but_2"), 
		nav_but_3 = globalPropertyi("tu154ce/buttons/ovhd/nav_2_but_3"), 
		nav_course = globalPropertyi("tu154ce/rotary/console/nav_2_course"), 
		vor_dme = globalPropertyf("tu154ce/radio/vor_dme_2"), 
		vor_bear = globalPropertyf("tu154ce/radio/vor_bear_2"), 
		nav_cs = globalPropertyf("tu154ce/radio/nav2_cs"),
		nav_gs = globalPropertyf("tu154ce/radio/nav2_gs"),
		nav_cs_flag = globalPropertyi("tu154ce/radio/nav2_cs_flag"),
		nav_gs_flag = globalPropertyi("tu154ce/radio/nav2_gs_flag"),
		nav_course_1 = globalPropertyf("tu154ce/rotary/console/nav_2_course_1"),
		nav_course_10 = globalPropertyf("tu154ce/rotary/console/nav_2_course_10"),
		nav_course_100 = globalPropertyf("tu154ce/rotary/console/nav_2_course_100"),
		nav_to_lit = globalPropertyf("tu154ce/lights/small/nav_2_to"),
		nav_from_lit = globalPropertyf("tu154ce/lights/small/nav_2_from"),
	},
	ark15 {},
	ark15 {
		left_freq = globalPropertyf("sim/cockpit2/radios/actuators/adf2_left_frequency_hz"),  
		right_freq = globalPropertyf("sim/cockpit2/radios/actuators/adf2_right_frequency_hz"),  
		active = globalPropertyf("sim/cockpit2/radios/actuators/adf2_right_is_selected"),  
		fail = globalPropertyf("sim/operation/failures/rel_adf2"),
		adf = globalPropertyf("sim/cockpit2/radios/indicators/adf2_relative_bearing_deg"),
		audio_selection = globalPropertyi("sim/cockpit2/radios/actuators/audio_selection_adf2"),
		ark_mode = globalPropertyi("tu154ce/switchers/ovhd/ark_2_mode"), 
		ark_channel = globalPropertyi("tu154ce/switchers/ovhd/ark_2_channel"), 
		ark_hundr_left = globalPropertyi("tu154ce/switchers/ovhd/ark_2_hundr_left"), 
		ark_tens_left = globalPropertyi("tu154ce/switchers/ovhd/ark_2_tens_left"), 
		ark_ones_left = globalPropertyi("tu154ce/switchers/ovhd/ark_2_ones_left"), 
		ark_hundr_right = globalPropertyi("tu154ce/switchers/ovhd/ark_2_hundr_right"), 
		ark_tens_right = globalPropertyi("tu154ce/switchers/ovhd/ark_2_tens_right"), 
		ark_ones_right = globalPropertyi("tu154ce/switchers/ovhd/ark_2_ones_right"), 
		ark_ramka = globalPropertyi("tu154ce/buttons/ovhd/ark_2_ramka"), 
		ark_left_lit = globalPropertyf("tu154ce/lights/ark2_left_lit"), 
		ark_right_lit = globalPropertyf("tu154ce/lights/ark2_right_lit"), 
		ark_all_lit = globalPropertyf("tu154ce/lights/ark2_all_lit"), 
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"),
		bus36_volt = globalPropertyf("tu154ce/elec/bus36_volt_right"),
		ark15_cc = globalPropertyf("tu154ce/radio/ark15_R_cc"), 
		adf_bear = globalPropertyf("tu154ce/radio/adf_bear_2"),
	},
	dme {
		position = {1616, 1176, 215, 70},
	},
	dme {
		position = {1616, 1102, 215, 70},
		vor_dme = globalPropertyf("tu154ce/radio/vor_dme_2"), 
		sd75_on = globalPropertyi("tu154ce/switchers/ovhd/sd75_2_on"), 
		nav_mile_km = globalPropertyi("tu154ce/switchers/nav_2_mile_km"), 
		dme_mile_lit = globalPropertyf("tu154ce/lights/small/dme_mile_right"), 
		dme_km_lit = globalPropertyf("tu154ce/lights/small/dme_km_right"), 
		bus27_volt = globalPropertyf("tu154ce/elec/bus27_volt_right"),
		bus115_volt = globalPropertyf("tu154ce/elec/bus115_3_volt"),
	},
	spu {},
	mrp {}, 
	radio_fails {},
}
