createGlobalPropertyi("sim/custom/lang/hide_rus_objects", 1) 
createGlobalPropertyi("sim/custom/lang/hide_eng_objects", 0) 
createGlobalPropertyi("sim/custom/have_pedals", 0) 
createGlobalPropertyi("sim/custom/sounds_voulme", 1000) 
createGlobalPropertyf("sim/custom/elec/bat_volt_1", 25) 
createGlobalPropertyf("sim/custom/elec/bat_volt_2", 25) 
createGlobalPropertyf("sim/custom/elec/bat_volt_3", 25) 
createGlobalPropertyf("sim/custom/elec/bat_volt_4", 25) 
createGlobalPropertyf("sim/custom/elec/bat_amp_1", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_amp_2", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_amp_3", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_amp_4", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_cc_1", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_cc_2", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_cc_3", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_cc_4", 0 ) 
createGlobalPropertyf("sim/custom/elec/bat_therm_1", 20 ) 
createGlobalPropertyf("sim/custom/elec/bat_therm_2", 20 ) 
createGlobalPropertyf("sim/custom/elec/bat_therm_3", 20 ) 
createGlobalPropertyf("sim/custom/elec/bat_therm_4", 20 ) 
createGlobalPropertyf("sim/custom/elec/vu1_volt", 27) 
createGlobalPropertyf("sim/custom/elec/vu2_volt", 27) 
createGlobalPropertyf("sim/custom/elec/vu_res_volt", 27) 
createGlobalPropertyf("sim/custom/elec/vu1_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/vu2_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/vu_res_amp", 0 ) 
createGlobalPropertyi("sim/custom/elec/vu_res_to_L", 0 ) 
createGlobalPropertyi("sim/custom/elec/vu_res_to_R", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus27_volt_left", 27) 
createGlobalPropertyf("sim/custom/elec/bus27_amp_left", 27) 
createGlobalPropertyf("sim/custom/elec/bus27_amp_right", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus27_volt_right", 0 ) 
createGlobalPropertyi("sim/custom/elec/bus27_source_left", 1) 
createGlobalPropertyi("sim/custom/elec/bus27_source_right", 0 ) 
createGlobalPropertyi("sim/custom/elec/bat_is_source_1", 1) 
createGlobalPropertyi("sim/custom/elec/bat_is_source_2", 1) 
createGlobalPropertyi("sim/custom/elec/bat_is_source_3", 1) 
createGlobalPropertyi("sim/custom/elec/bat_is_source_4", 1) 
createGlobalPropertyi("sim/custom/elec/bus_connected", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus36_volt_left", 36) 
createGlobalPropertyf("sim/custom/elec/bus36_volt_right", 36) 
createGlobalPropertyf("sim/custom/elec/bus36_volt_pts250_1", 36) 
createGlobalPropertyf("sim/custom/elec/bus36_volt_pts250_2", 36) 
createGlobalPropertyf("sim/custom/elec/bus36_amp_left", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus36_amp_right", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus36_amp_pts250_1", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus36_amp_pts250_2", 0 ) 
createGlobalPropertyi("sim/custom/elec/bus36_tr1_work", 1) 
createGlobalPropertyi("sim/custom/elec/bus36_tr2_work", 1) 
createGlobalPropertyi("sim/custom/elec/bus36_pts1_work", 1) 
createGlobalPropertyi("sim/custom/elec/bus36_pts2_work", 0 ) 
createGlobalPropertyi("sim/custom/elec/bus36_src_L", 0 ) 
createGlobalPropertyi("sim/custom/elec/bus36_src_R", 0 ) 
createGlobalPropertyi("sim/custom/elec/gen1_work", 1) 
createGlobalPropertyi("sim/custom/elec/gen2_work", 1) 
createGlobalPropertyi("sim/custom/elec/gen3_work", 1) 
createGlobalPropertyi("sim/custom/elec/gen4_work", 0 ) 
createGlobalPropertyi("sim/custom/elec/gpu_work", 0 ) 
createGlobalPropertyi("sim/custom/elec/gen1_overload", 0 ) 
createGlobalPropertyi("sim/custom/elec/gen2_overload", 0 ) 
createGlobalPropertyi("sim/custom/elec/gen3_overload", 0 ) 
createGlobalPropertyi("sim/custom/elec/gen4_overload", 0 ) 
createGlobalPropertyi("sim/custom/elec/gpu_overload", 0 ) 
createGlobalPropertyf("sim/custom/elec/gen1_volt", 115) 
createGlobalPropertyf("sim/custom/elec/gen2_volt", 115) 
createGlobalPropertyf("sim/custom/elec/gen3_volt", 115) 
createGlobalPropertyf("sim/custom/elec/gen4_volt", 115) 
createGlobalPropertyf("sim/custom/elec/gpu_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_1_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_2_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_3_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_em_1_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_em_2_volt", 115) 
createGlobalPropertyf("sim/custom/elec/bus115_1_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus115_2_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus115_3_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus115_em_1_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/bus115_em_2_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/gen1_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/gen2_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/gen3_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/gen4_amp", 0 ) 
createGlobalPropertyf("sim/custom/elec/gpu_amp", 0 ) 
createGlobalPropertyf("sim/custom/thermo/cockpit_temp", 20 ) 
createGlobalPropertyf("sim/custom/thermo/cabin1_temp", 20 ) 
createGlobalPropertyf("sim/custom/thermo/cabin2_temp", 20 ) 
createGlobalPropertyf("sim/custom/elec/apu_start_bus", 27) 
createGlobalPropertyf("sim/custom/elec/apu_start_cc", 0 ) 
createGlobalPropertyi("sim/custom/elec/apu_start_seq", 0 ) 
createGlobalPropertyf("sim/custom/elec/apu_burning_fuel", 0 ) 
createGlobalPropertyf("sim/custom/elec/cockpit_light_cc_left", 0 ) 
createGlobalPropertyf("sim/custom/elec/cockpit_light_cc_right", 0 ) 
createGlobalPropertyf("sim/custom/elec/cockpit_light_cc_115", 0 ) 
createGlobalPropertyf("sim/custom/elec/ext_light_cc_left", 0 ) 
createGlobalPropertyf("sim/custom/elec/ext_light_cc_right", 0 ) 
createGlobalPropertyf("sim/custom/elec/ext_light_cc_115", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_n1", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_oil_t", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_oil_q", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_oil_p", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_fuel_p", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_egt", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_air_press", 0 ) 
createGlobalPropertyf("sim/custom/eng/apu_air_doors", 0 ) 
createGlobalPropertyi("sim/custom/eng/apu_system_on", 0 ) 
createGlobalPropertyf("sim/custom/eng/vibration_1", 0 ) 
createGlobalPropertyf("sim/custom/eng/vibration_2", 0 ) 
createGlobalPropertyf("sim/custom/eng/vibration_3", 0 ) 
createGlobalPropertyi("sim/custom/fuel/eng_fuel_press_1", 1) 
createGlobalPropertyi("sim/custom/fuel/eng_fuel_press_2", 1) 
createGlobalPropertyi("sim/custom/fuel/eng_fuel_press_3", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank2_left_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank2_right_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank3_left_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank3_right_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank4_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank1_1_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank1_2_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank1_3_work", 1) 
createGlobalPropertyi("sim/custom/fuel/pump_tank1_4_work", 1) 
createGlobalPropertyi("sim/custom/fuel/reserv_trans", 0 ) 
createGlobalPropertyi("sim/custom/fuel/auto_tanks_turn", 0 ) 
createGlobalPropertyi("sim/custom/fuel/auto_tank_level_2", 0) 
createGlobalPropertyi("sim/custom/fuel/auto_tank_level_3", 0															) 
createGlobalPropertyf("sim/custom/fuel/fire_vlv_open_1", 1) 
createGlobalPropertyf("sim/custom/fuel/fire_vlv_open_2", 1) 
createGlobalPropertyf("sim/custom/fuel/fire_vlv_open_3", 1) 
createGlobalPropertyf("sim/custom/elec/fuel_pumps_115_1_cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/fuel_pumps_115_3_cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/fuel_pumps_27_cc", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_press_1", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_press_2", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_press_3", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_press_4", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_qty_1", 55) 
createGlobalPropertyf("sim/custom/hydro/gs_qty_2", 55) 
createGlobalPropertyf("sim/custom/hydro/gs_qty_3", 49) 
createGlobalPropertyf("sim/custom/hydro/gs_qty_12_show", 48) 
createGlobalPropertyf("sim/custom/hydro/gs_qty_3_show", 24) 
createGlobalPropertyf("sim/custom/hydro/gs_pump_2_cc", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_pump_3_cc", 0 ) 
createGlobalPropertyf("sim/custom/hydro/gs_bak_qty_1", 17.17) 
createGlobalPropertyf("sim/custom/hydro/gs_bak_qty_2", 17.17) 
createGlobalPropertyf("sim/custom/hydro/gs_bak_qty_3", 23.8) 
createGlobalPropertyf("sim/custom/bleed/air_usage_L", 0 ) 
createGlobalPropertyf("sim/custom/bleed/air_usage_R", 0 ) 
createGlobalPropertyf("sim/custom/bleed/eng_airvalve_1", 1) 
createGlobalPropertyf("sim/custom/bleed/eng_airvalve_2", 1) 
createGlobalPropertyf("sim/custom/bleed/eng_airvalve_3", 1) 
createGlobalPropertyf("sim/custom/bleed/hot_tube_t", 100 ) 
createGlobalPropertyf("sim/custom/bleed/door_heat_tube_t", 80 ) 
createGlobalPropertyf("sim/custom/bleed/cockpit_tube_t", 30 ) 
createGlobalPropertyf("sim/custom/bleed/cabin1_tube_t", 30 ) 
createGlobalPropertyf("sim/custom/bleed/cabin2_tube_t", 30 ) 
createGlobalPropertyf("sim/custom/bleed/cold_tube1_t", 30 ) 
createGlobalPropertyf("sim/custom/bleed/cold_tube2_t", 30 ) 
createGlobalPropertyf("sim/custom/bleed/cockpit_temp", 20 ) 
createGlobalPropertyf("sim/custom/bleed/cabin_1_temp", 20 ) 
createGlobalPropertyf("sim/custom/bleed/cabin_2_temp", 20 ) 
createGlobalPropertyf("sim/custom/start/starter_pressure", 0 ) 
createGlobalPropertyi("sim/custom/start/apd_working_1", 0 ) 
createGlobalPropertyi("sim/custom/start/apd_working_2", 0 ) 
createGlobalPropertyi("sim/custom/start/apd_working_3", 0 ) 
createGlobalPropertyi("sim/custom/start/start_sys_work", 0 ) 
createGlobalPropertyi("sim/custom/start/fuel_in_1", 1) 
createGlobalPropertyi("sim/custom/start/fuel_in_2", 1) 
createGlobalPropertyi("sim/custom/start/fuel_in_3", 1) 
createGlobalPropertyf("sim/custom/trimmers/int_pitch_trim", 0 ) 
createGlobalPropertyf("sim/custom/trimmers/int_roll_trim", 0 ) 
createGlobalPropertyf("sim/custom/trimmers/int_yaw_trim", 0 ) 
createGlobalPropertyf("sim/custom/controls/control_force_pos", 0) 
createGlobalPropertyf("sim/custom/controls/control_force_pos_rud", 0	) 
createGlobalPropertyi("sim/custom/fire/ext_used_1", 0 ) 
createGlobalPropertyi("sim/custom/fire/ext_used_2", 0 ) 
createGlobalPropertyi("sim/custom/fire/ext_used_3", 0 ) 
createGlobalPropertyi("sim/custom/fire/ng_used", 0 ) 
createGlobalPropertyi("sim/custom/fire/valve_open_1", 0 ) 
createGlobalPropertyi("sim/custom/fire/valve_open_2", 0 ) 
createGlobalPropertyi("sim/custom/fire/valve_open_3", 0 ) 
createGlobalPropertyi("sim/custom/fire/valve_open_4", 0 ) 
createGlobalPropertyi("sim/custom/fire/fire_siren", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fire_state_1", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fire_state_2", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fire_state_3", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fire_state_4", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fuel_cut_1", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fuel_cut_2", 0 ) 
createGlobalPropertyi("sim/custom/fire/engine_fuel_cut_3", 0 ) 
createGlobalPropertyi("sim/custom/fire/fire_detected", 0 ) 
createGlobalPropertyf("sim/custom/fire/fire_sys_cc", 0 ) 
createGlobalPropertyf("sim/custom/antiice/wing_heat_t", 15) 
createGlobalPropertyf("sim/custom/antiice/stab_heat_t", 15) 
createGlobalPropertyi("sim/custom/antiice/ice_detected", 0 ) 
createGlobalPropertyi("sim/custom/antiice/ice_detect_ok", 0 ) 
createGlobalPropertyi("sim/custom/antiice/wing_heating", 1) 
createGlobalPropertyi("sim/custom/antiice/slat_heating", 1) 
createGlobalPropertyf("sim/custom/antiice/ai_27_L_cc", 0 ) 
createGlobalPropertyf("sim/custom/antiice/ai_27_R_cc", 0 ) 
createGlobalPropertyf("sim/custom/antiice/ai_115_1_cc", 0 ) 
createGlobalPropertyf("sim/custom/antiice/ai_115_2_cc", 0 ) 
createGlobalPropertyf("sim/custom/antiice/ai_115_3_cc", 0) 
createGlobalPropertyi("sim/custom/antiice/eng_heat_open_1", 0) 
createGlobalPropertyi("sim/custom/antiice/eng_heat_open_2", 0) 
createGlobalPropertyi("sim/custom/antiice/eng_heat_open_3", 0															) 
createGlobalPropertyi("sim/custom/msrp/msrp_power", 1) 
createGlobalPropertyi("sim/custom/msrp/msrp_recording", 1) 
createGlobalPropertyf("sim/custom/msrp/msrp_27_L_cc", 0 ) 
createGlobalPropertyf("sim/custom/msrp/msrp_27_R_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_27_L_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_27_R_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_115_1_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_115_2_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_115_3_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_36L_cc", 0 ) 
createGlobalPropertyf("sim/custom/control/ctr_36R_cc", 0 ) 
createGlobalPropertyi("sim/custom/auasp/alpha_critical", 0 ) 
createGlobalPropertyi("sim/custom/auasp/gforce_critical", 0 ) 
createGlobalPropertyf("sim/custom/gyro/mgv_contr_roll", 0 ) 
createGlobalPropertyf("sim/custom/gyro/mgv_contr_pitch", 0 ) 
createGlobalPropertyi("sim/custom/gyro/mgv_contr_flag", 0 ) 
createGlobalPropertyi("sim/custom/bkk/left_roll_big", 0 ) 
createGlobalPropertyi("sim/custom/bkk/right_roll_big", 0 ) 
createGlobalPropertyi("sim/custom/bkk/mgv_contr_fail", 0 ) 
createGlobalPropertyi("sim/custom/bkk/no_contr_ag", 0 ) 
createGlobalPropertyi("sim/custom/bkk/pkp_fail_left", 0 ) 
createGlobalPropertyi("sim/custom/bkk/pkp_fail_right", 0 ) 
createGlobalPropertyf("sim/custom/bkk/pkp_roll_left", 0 ) 
createGlobalPropertyf("sim/custom/bkk/pkp_roll_right", 0 ) 
createGlobalPropertyf("sim/custom/bkk/pkp_left_power_cc", 0 ) 
createGlobalPropertyf("sim/custom/bkk/pkp_right_power_cc", 0 ) 
createGlobalPropertyf("sim/custom/bkk/mgv_ctr_power_cc", 0 ) 
createGlobalPropertyf("sim/custom/gyro/ahz_pitch_int_L", 0) 
createGlobalPropertyf("sim/custom/gyro/ahz_pitch_int_R", 0		) 
createGlobalPropertyi("sim/custom/tcas/range_set", 3) 
createGlobalPropertyi("sim/custom/tcas/mode_set", 4) 
createGlobalPropertyi("sim/custom/tcas/screen_mode", 0 ) 
createGlobalPropertyi("sim/custom/tcas/level_mode", 0 ) 
createGlobalPropertyi("sim/custom/tcas/fl_mode", 0 ) 
createGlobalPropertyi("sim/custom/tcas/flt_id", 0 ) 
createGlobalPropertyi("sim/custom/tcas/ra_scale_set", 0 ) 
createGlobalPropertyi("sim/custom/tcas/traffic_det", 0 ) 
createGlobalPropertyf("sim/custom/svs/altitude", 0 ) 
createGlobalPropertyf("sim/custom/svs/machno", 0 ) 
createGlobalPropertyf("sim/custom/svs/true_airspeed", 0 ) 
createGlobalPropertyf("sim/custom/svs/power_27cc", 0 ) 
createGlobalPropertyf("sim/custom/svs/power_36cc", 0 ) 
createGlobalPropertyf("sim/custom/svs/power_115cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/auasp_pow27_cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/auasp_pow115_cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/rv5_left_cc", 0 ) 
createGlobalPropertyf("sim/custom/elec/rv5_right_cc", 0 ) 
createGlobalPropertyf("sim/custom/misc/rv5_alt_left", 0 ) 
createGlobalPropertyf("sim/custom/misc/rv5_alt_right", 0) 
createGlobalPropertyi("sim/custom/misc/rv5_dh_signal_left", 0 ) 
createGlobalPropertyi("sim/custom/misc/rv5_dh_signal_right", 0 ) 
createGlobalPropertyi("sim/custom/taws/mode_set", 1) 
createGlobalPropertyi("sim/custom/taws/distance_set", 0 ) 
createGlobalPropertyf("sim/custom/taws/taws_cc", 0 ) 
createGlobalPropertyi("sim/custom/taws/taws_message", 0 ) 
createGlobalPropertyi("sim/custom/taws/taws_english", 0 ) 
createGlobalPropertyf("sim/custom/taws/gs_msg_int", 5) 
createGlobalPropertyf("sim/custom/taws/gs_msg_vol", 1) 
createGlobalPropertyi("sim/custom/taws/taws_alt_left", 0 ) 
createGlobalPropertyi("sim/custom/taws/taws_alt_right", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_mk_1", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_mk_2", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_ga_1", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_ga_2", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_bgmk_1", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_bgmk_2", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_gpk", 0 ) 
createGlobalPropertyf("sim/custom/tks/course_gmk", 0 ) 
createGlobalPropertyi("sim/custom/tks/fail_left", 0 ) 
createGlobalPropertyi("sim/custom/tks/fail_right", 0 ) 
createGlobalPropertyf("sim/custom/nvu/diss_wind_course", 0 ) 
createGlobalPropertyf("sim/custom/nvu/diss_wind_spd", 0 ) 
createGlobalPropertyf("sim/custom/nvu/diss_groundspeed", 0 ) 
createGlobalPropertyf("sim/custom/nvu/diss_slip_angle", 0 ) 
createGlobalPropertyi("sim/custom/nvu/diss_mode", 1) 
createGlobalPropertyf("sim/custom/rsbn/distance", 0 ) 
createGlobalPropertyf("sim/custom/rsbn/azimuth", 0 ) 
createGlobalPropertyf("sim/custom/radio/adf_bear_1", 0 ) 
createGlobalPropertyf("sim/custom/radio/adf_bear_2", 0 ) 
createGlobalPropertyf("sim/custom/radio/vor_bear_1", 0 ) 
createGlobalPropertyf("sim/custom/radio/vor_bear_2", 0 ) 
createGlobalPropertyf("sim/custom/radio/vor_dme_1", 0 ) 
createGlobalPropertyf("sim/custom/radio/vor_dme_2", 0 ) 
createGlobalPropertyf("sim/custom/radio/nav1_cs", 0 ) 
createGlobalPropertyf("sim/custom/radio/nav1_gs", 0 ) 
createGlobalPropertyf("sim/custom/radio/nav2_cs", 0 ) 
createGlobalPropertyf("sim/custom/radio/nav2_gs", 0 ) 
createGlobalPropertyi("sim/custom/radio/nav1_cs_flag", 0 ) 
createGlobalPropertyi("sim/custom/radio/nav2_cs_flag", 0 ) 
createGlobalPropertyi("sim/custom/radio/nav1_gs_flag", 0 ) 
createGlobalPropertyi("sim/custom/radio/nav2_gs_flag", 0 ) 
createGlobalPropertyf("sim/custom/nvu/current_Z1", 0 ) 
createGlobalPropertyf("sim/custom/nvu/current_S1", 0 ) 
createGlobalPropertyf("sim/custom/nvu/next_Z1", 0 ) 
createGlobalPropertyf("sim/custom/nvu/next_S1", 0 ) 
createGlobalPropertyf("sim/custom/nvu/current_Z2", 0 ) 
createGlobalPropertyf("sim/custom/nvu/current_S2", 0 ) 
createGlobalPropertyf("sim/custom/nvu/next_Z2", 0 ) 
createGlobalPropertyf("sim/custom/nvu/next_S2", 0 ) 
createGlobalPropertyf("sim/custom/nvu/zpu1", 0 ) 
createGlobalPropertyf("sim/custom/nvu/zpu2", 0 ) 
createGlobalPropertyi("sim/custom/nvu/nvu_mode", 1) 
createGlobalPropertyi("sim/custom/nvu/nvu_active", 1) 
createGlobalPropertyf("sim/custom/nvu/nvu_res_course", 0 ) 
createGlobalPropertyf("sim/custom/nvu/nvu_res_z", 0 ) 
createGlobalPropertyi("sim/custom/nvu/nvu_changing_ort", 0 ) 
createGlobalPropertyi("sim/custom/nvu/nvu_fail", 0 ) 
createGlobalPropertyi("sim/custom/absu/roll_main_mode", 1) 
createGlobalPropertyi("sim/custom/absu/pitch_main_mode", 1) 
createGlobalPropertyi("sim/custom/absu/roll_sub_mode", 0 ) 
createGlobalPropertyi("sim/custom/absu/pitch_sub_mode", 0 ) 
createGlobalPropertyf("sim/custom/absu/contr_pitch", 0 ) 
createGlobalPropertyf("sim/custom/absu/contr_roll", 0 ) 
createGlobalPropertyf("sim/custom/absu/contr_yaw", 0 ) 
createGlobalPropertyf("sim/custom/bkk/bkk_pitch", 0 ) 
createGlobalPropertyf("sim/custom/bkk/bkk_roll", 0 ) 
createGlobalPropertyi("sim/custom/absu/absu_pitch_trimm", 0 ) 
createGlobalPropertyf("sim/custom/absu/rud_1_spd", 0 ) 
createGlobalPropertyf("sim/custom/absu/rud_2_spd", 0 ) 
createGlobalPropertyf("sim/custom/absu/rud_3_spd", 0 ) 
createGlobalPropertyf("sim/custom/absu/absu_roll_ind", 0 ) 
createGlobalPropertyf("sim/custom/absu/absu_pitch_ind", 0 ) 
createGlobalPropertyi("sim/custom/absu/absu_roll_flag", 1) 
createGlobalPropertyi("sim/custom/absu/absu_pitch_flag", 1) 
createGlobalPropertyi("sim/custom/absu/absu_pnp_mode_1", 0 ) 
createGlobalPropertyi("sim/custom/absu/absu_pnp_mode_2", 0 ) 
createGlobalPropertyi("sim/custom/absu/stu_mode", 0) 
createGlobalPropertyi("sim/custom/absu/toga_comm", 0 ) 
createGlobalPropertyf("sim/custom/absu_at_dif_left", 0 ) 
createGlobalPropertyf("sim/custom/absu_at_dif_right", 0 ) 
createGlobalPropertyi("sim/custom/absu_course_out", 0 ) 
createGlobalPropertyi("sim/custom/absu_gs_out", 0 ) 
createGlobalPropertyf("sim/custom/absu_power_cc", 0	) 
createGlobalPropertyf("sim/custom/absu_at_power_cc", 0) 
createGlobalPropertyi("sim/custom/absu_use_second_nav", 0) 
createGlobalPropertyi("sim/custom/absu/damp_roll_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/damp_pitch_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/damp_yaw_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/roll_contr_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/pitch_contr_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/man_roll_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/man_pitch_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/man_toga_lamp", 0) 
createGlobalPropertyi("sim/custom/absu/triangle_lamp_signal", 0) 
createGlobalPropertyi("sim/custom/absu/absu_fail_signal", 0) 
createGlobalPropertyf("sim/custom/kln90/kln_course", 0 ) 
createGlobalPropertyf("sim/custom/kln90/kln_dev", 0 ) 
createGlobalPropertyi("sim/custom/kln90/kln_flag", 0 ) 
createGlobalPropertyf("sim/custom/radio/vhf1_cc", 0) 
createGlobalPropertyf("sim/custom/radio/vhf2_cc", 0) 
createGlobalPropertyf("sim/custom/tks/km5_1_cc", 0) 
createGlobalPropertyf("sim/custom/tks/km5_2_cc", 0) 
createGlobalPropertyf("sim/custom/tks/ga_1_cc", 0) 
createGlobalPropertyf("sim/custom/tks/ga_2_cc", 0) 
createGlobalPropertyf("sim/custom/tks/ga_heat_cc", 0) 
createGlobalPropertyf("sim/custom/tks/bgmk_1_cc", 0) 
createGlobalPropertyf("sim/custom/tks/bgmk_2_cc", 0) 
createGlobalPropertyf("sim/custom/tks/ush_cc", 0) 
createGlobalPropertyf("sim/custom/ahz/agr_cc", 0) 
createGlobalPropertyf("sim/custom/nvu/nvu_cc", 0) 
createGlobalPropertyf("sim/custom/radio/ark15_L_cc", 0) 
createGlobalPropertyf("sim/custom/radio/ark15_R_cc", 0) 
createGlobalPropertyf("sim/custom/nvu/diss_cc", 0) 
createGlobalPropertyf("sim/custom/radio/nav1_pow_cc", 0) 
createGlobalPropertyf("sim/custom/radio/nav2_pow_cc", 0) 
createGlobalPropertyf("sim/custom/radio/radar_cc", 0) 
createGlobalPropertyf("sim/custom/radio/rsbn_cc", 0) 
createGlobalPropertyi("sim/custom/payload/crew_num", 3) 
createGlobalPropertyi("sim/custom/payload/zone_1", 9) 
createGlobalPropertyi("sim/custom/payload/zone_2", 22) 
createGlobalPropertyi("sim/custom/payload/cabin_num", 4) 
createGlobalPropertyi("sim/custom/payload/zone_4", 24) 
createGlobalPropertyi("sim/custom/payload/zone_5", 21) 
createGlobalPropertyi("sim/custom/payload/zone_6", 7) 
createGlobalPropertyi("sim/custom/payload/cargo_1", 2500) 
createGlobalPropertyi("sim/custom/payload/cargo_2", 1200) 
createGlobalPropertyi("sim/custom/payload/kitchens", 300) 
createGlobalPropertyi("sim/custom/payload/various", 50) 
createGlobalPropertyi("sim/custom/payload/main_dist", 1000) 
createGlobalPropertyi("sim/custom/payload/alt_dist", 500) 
createGlobalPropertyi("sim/custom/payload/main_fl", 380) 
createGlobalPropertyi("sim/custom/payload/alt_fl", 320) 
createGlobalPropertyi("sim/custom/payload/nav_fuel", 2500) 
createGlobalPropertyi("sim/custom/payload/taxi_fuel", 100) 
createGlobalPropertyi("sim/custom/payload/tank_1", 3300) 
createGlobalPropertyi("sim/custom/payload/tank_4", 0) 
createGlobalPropertyi("sim/custom/payload/tank_2L", 1500) 
createGlobalPropertyi("sim/custom/payload/tank_2R", 1500) 
createGlobalPropertyi("sim/custom/payload/tank_3L", 3225) 
createGlobalPropertyi("sim/custom/payload/tank_3R", 3225) 
createGlobalPropertyi("sim/custom/payload/load_fuel_btn", 0) 
createGlobalPropertyi("sim/custom/payload/load_fast_btn", 0) 
createGlobalPropertyi("sim/custom/payload/load_slow_btn", 0) 
createGlobalPropertyf("sim/custom/payload/paylod_set", 0) 
createGlobalPropertyf("sim/custom/payload/cg_set", 0) 
createGlobalPropertyi("sim/custom/sounds/taws_eng_phrase", 0) 
createGlobalPropertyi("sim/custom/sounds/taws_rus_phrase", 0) 
createGlobalPropertyi("sim/custom/sounds/enable_crew_vo", 1) 
createGlobalPropertyi("sim/custom/alarm/main_gear_flaps", 0) 
createGlobalPropertyi("sim/custom/alarm/main_pressure", 0) 
createGlobalPropertyi("sim/custom/alarm/speaker_auasp", 0) 
createGlobalPropertyi("sim/custom/alarm/speaker_fuel", 0) 
createGlobalPropertyi("sim/custom/alarm/speaker_speed", 0) 
createGlobalPropertyi("sim/custom/alarm/speaker_absu", 0) 
createGlobalPropertyi("sim/custom/checklist/side", 0) 
createGlobalPropertyi("sim/custom/checklist/fishka_1", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_2", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_3", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_4", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_5", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_6", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_7", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_8", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_9", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_10", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_11", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_12", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_13", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_14", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_15", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_16", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_17", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_18", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_19", 1) 
createGlobalPropertyi("sim/custom/checklist/fishka_20", 1) 
createGlobalPropertyi("sim/custom/panels/show_load_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_absu_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_ohvd_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_nvu_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_checklist_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_ground_panel", 0) 
createGlobalPropertyi("sim/custom/panels/show_phone", 0) 
createGlobalPropertyi("sim/custom/panels/show_cam", 0) 
createGlobalPropertyi("sim/custom/panels/show_palette", 0) 
createGlobalPropertyi("sim/custom/panels/show_fail_panel", 0) 
createGlobalPropertyf("sim/custom/misc/cg_pos_actual", 0) 
createGlobalPropertyf("sim/custom/misc/weight_actual", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_1_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_2_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_3_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_4_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_5_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_1_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_2_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_3_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_4_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_5_L", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_1_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_2_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_3_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_4_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_1_w_5_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_1_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_2_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_3_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_4_R", 0) 
createGlobalPropertyf("sim/custom/anim/rain_glass_2_w_5_R", 0) 
createGlobalPropertyf("sim/custom/anim/net_rain_ratio", 0) 
createGlobalPropertyf("sim/custom/misc/water_level", 0) 
createGlobalPropertyf("sim/custom/gauges/alt/vbe_flightlevel_left", 0) 
createGlobalPropertyf("sim/custom/gauges/alt/vbe_flightlevel_right", 0) 
createGlobalPropertyf("sim/custom/brakes/int_brakes_L", 0) 
createGlobalPropertyf("sim/custom/brakes/int_brakes_R", 0) 
createGlobalPropertyf("sim/custom/gauges/vvi_left", 0) 
createGlobalPropertyf("sim/custom/gauges/vvi_right", 0) 
createGlobalPropertyi("sim/custom/SC/control_thro_other", 0) 
createGlobalPropertyf("sim/custom/SC/yoke_pitch_ratio", 0) 
createGlobalPropertyf("sim/custom/SC/yoke_roll_ratio", 0) 
createGlobalPropertyf("sim/custom/SC/yoke_heading_ratio", 0) 
createGlobalPropertyf("sim/custom/SC/engine/ENGN_thro_0", 0) 
createGlobalPropertyf("sim/custom/SC/engine/ENGN_thro_1", 0) 
createGlobalPropertyf("sim/custom/SC/engine/ENGN_thro_2", 0) 
createGlobalPropertyf("sim/custom/SC/engine/ENGN_propmode_0", 0) 
createGlobalPropertyf("sim/custom/SC/engine/ENGN_propmode_2", 0) 
createGlobalPropertyf("sim/custom/SC/gear/tire_steer_command_deg", 0) 
createGlobalPropertyf("sim/custom/SC/controls/l_brake_add", 0) 
createGlobalPropertyf("sim/custom/SC/controls/r_brake_add", 0) 
createGlobalPropertyf("sim/custom/SC/brakes/int_brakes_L", 0) 
createGlobalPropertyf("sim/custom/SC/brakes/int_brakes_R", 0) 
createGlobalPropertyf("sim/custom/SC/controls/parkbrake", 0) 
createGlobalPropertyi("sim/custom/speeds/v1_15", 0) 
createGlobalPropertyi("sim/custom/speeds/vr_15", 0) 
createGlobalPropertyi("sim/custom/speeds/v2_15", 0) 
createGlobalPropertyi("sim/custom/speeds/v1_28", 0) 
createGlobalPropertyi("sim/custom/speeds/vr_28", 0) 
createGlobalPropertyi("sim/custom/speeds/v2_28", 0) 
createGlobalPropertyi("sim/custom/checklist/checklist_selected", 0) 
createGlobalPropertyi("sim/custom/checklist/to_ready", 0) 
createGlobalPropertyi("sim/custom/sound/reset_crew", 0) 
createGlobalPropertyf("sim/custom/SC/GNS430_dtk", 0) 
createGlobalPropertyf("sim/custom/SC/GNS430_dev", 0) 
createGlobalPropertyi("sim/custom/SC/GNS430_flag", 0) 

