defineProperty("frame_time", globalPropertyf("sim/custom/time/frame_time")) 
defineProperty("absu_roll_mode", globalPropertyi("sim/custom/gauges/console/absu_roll_mode")) 
defineProperty("absu_pitch_mode", globalPropertyi("sim/custom/gauges/console/absu_pitch_mode")) 
defineProperty("absu_zpu_sel", globalPropertyi("sim/custom/switchers/console/absu_zpu_sel")) 
defineProperty("absu_nav_on", globalPropertyi("sim/custom/switchers/console/absu_nav_on")) 
defineProperty("absu_landing_on", globalPropertyi("sim/custom/switchers/console/absu_landing_on")) 
defineProperty("absu_needles_on", globalPropertyi("sim/custom/switchers/console/absu_needles_on")) 
defineProperty("absu_speed_mode", globalPropertyi("sim/custom/switchers/console/absu_speed_mode")) 
defineProperty("absu_speed_change", globalPropertyi("sim/custom/switchers/console/absu_speed_change")) 
defineProperty("absu_speed_off", globalPropertyi("sim/custom/switchers/console/absu_speed_off")) 
defineProperty("absu_speed_prepare", globalPropertyi("sim/custom/switchers/console/absu_speed_prepare")) 
defineProperty("absu_speed_us_right_left", globalPropertyi("sim/custom/switchers/console/absu_speed_us_right_left")) 
defineProperty("absu_roll_ch_on", globalPropertyi("sim/custom/switchers/console/absu_roll_ch_on")) 
defineProperty("absu_pitch_ch_on", globalPropertyi("sim/custom/switchers/console/absu_pitch_ch_on")) 
defineProperty("absu_smooth_on", globalPropertyi("sim/custom/switchers/console/absu_smooth_on")) 
defineProperty("absu_turn_handle", globalPropertyi("sim/custom/switchers/console/absu_turn_handle")) 
defineProperty("absu_pitch_wheel", globalPropertyf("sim/custom/switchers/console/absu_pitch_wheel")) 
defineProperty("absu_pitch_wheel_dir", globalPropertyi("sim/custom/switchers/console/absu_pitch_wheel_dir")) 
defineProperty("hydro_ra56_rud_1", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_rud_1")) 
defineProperty("hydro_ra56_rud_2", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_rud_2")) 
defineProperty("hydro_ra56_rud_3", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_rud_3")) 
defineProperty("hydro_ra56_ail_1", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_ail_1")) 
defineProperty("hydro_ra56_ail_2", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_ail_2")) 
defineProperty("hydro_ra56_ail_3", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_ail_3")) 
defineProperty("hydro_ra56_elev_1", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_elev_1")) 
defineProperty("hydro_ra56_elev_2", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_elev_2")) 
defineProperty("hydro_ra56_elev_3", globalPropertyi("sim/custom/switchers/eng/hydro_ra56_elev_3")) 
defineProperty("hydro_circuit_auto_man", globalPropertyi("sim/custom/switchers/eng/hydro_circuit_auto_man")) 
defineProperty("hydro_long_control", globalPropertyi("sim/custom/switchers/eng/hydro_long_control")) 
defineProperty("hydro_circuit_auto_man_cap", globalPropertyi("sim/custom/switchers/eng/hydro_circuit_auto_man_cap")) 
defineProperty("hydro_long_control_cap", globalPropertyi("sim/custom/switchers/eng/hydro_long_control_cap")) 
defineProperty("ZK_select", globalPropertyi("sim/custom/switchers/ZK_select")) 
defineProperty("nav_select", globalPropertyi("sim/custom/switchers/nav_select")) 
defineProperty("vbe_select", globalPropertyi("sim/custom/switchers/vbe_select")) 
defineProperty("absu_zk", globalPropertyi("sim/custom/buttons/console/absu_zk")) 
defineProperty("absu_reset", globalPropertyi("sim/custom/buttons/console/absu_reset")) 
defineProperty("absu_nvu", globalPropertyi("sim/custom/buttons/console/absu_nvu")) 
defineProperty("absu_az1", globalPropertyi("sim/custom/buttons/console/absu_az1")) 
defineProperty("absu_az2", globalPropertyi("sim/custom/buttons/console/absu_az2")) 
defineProperty("absu_app", globalPropertyi("sim/custom/buttons/console/absu_app")) 
defineProperty("absu_gs", globalPropertyi("sim/custom/buttons/console/absu_gs")) 
defineProperty("absu_stab_m", globalPropertyi("sim/custom/buttons/console/absu_stab_m")) 
defineProperty("absu_stab_v", globalPropertyi("sim/custom/buttons/console/absu_stab_v")) 
defineProperty("absu_stab_h", globalPropertyi("sim/custom/buttons/console/absu_stab_h")) 
defineProperty("absu_stab", globalPropertyi("sim/custom/buttons/console/absu_stab")) 
defineProperty("absu_arrest", globalPropertyi("sim/custom/buttons/console/absu_arrest")) 
defineProperty("absu_speed_test_1", globalPropertyi("sim/custom/buttons/console/absu_speed_test_1")) 
defineProperty("absu_speed_test_2", globalPropertyi("sim/custom/buttons/console/absu_speed_test_2")) 
defineProperty("absu_stab_speed", globalPropertyi("sim/custom/buttons/console/absu_stab_speed")) 
defineProperty("absu_throt_off_1", globalPropertyi("sim/custom/buttons/console/absu_throt_off_1")) 
defineProperty("absu_throt_off_2", globalPropertyi("sim/custom/buttons/console/absu_throt_off_2")) 
defineProperty("absu_throt_off_3", globalPropertyi("sim/custom/buttons/console/absu_throt_off_3")) 
defineProperty("absu_arrest_cap", globalPropertyi("sim/custom/buttons/console/absu_arrest_cap")) 
defineProperty("absu_smooth_on_cap", globalPropertyi("sim/custom/switchers/console/absu_smooth_on_cap")) 
defineProperty("absu_speed_prepare_cap", globalPropertyi("sim/custom/switchers/console/absu_speed_prepare_cap")) 
defineProperty("absu_speed_off_cap", globalPropertyi("sim/custom/switchers/console/absu_speed_off_cap")) 
defineProperty("absu_zk_lamp", globalPropertyf("sim/custom/lights/button/absu_zk")) 
defineProperty("absu_reset_lamp", globalPropertyf("sim/custom/lights/button/absu_reset")) 
defineProperty("absu_nvu_lamp", globalPropertyf("sim/custom/lights/button/absu_nvu")) 
defineProperty("absu_az1_lamp", globalPropertyf("sim/custom/lights/button/absu_az1")) 
defineProperty("absu_az2_lamp", globalPropertyf("sim/custom/lights/button/absu_az2")) 
defineProperty("absu_app_lamp", globalPropertyf("sim/custom/lights/button/absu_app")) 
defineProperty("absu_gz_lamp", globalPropertyf("sim/custom/lights/button/absu_gz")) 
defineProperty("absu_stab_m_lamp", globalPropertyf("sim/custom/lights/button/absu_stab_m")) 
defineProperty("absu_stab_v_lamp", globalPropertyf("sim/custom/lights/button/absu_stab_v")) 
defineProperty("absu_stab_h_lamp", globalPropertyf("sim/custom/lights/button/absu_stab_h")) 
defineProperty("absu_stab_lamp", globalPropertyf("sim/custom/lights/button/absu_stab")) 
defineProperty("absu_stab_spd_lamp", globalPropertyf("sim/custom/lights/button/absu_stab_spd")) 
defineProperty("absu_thro1_lamp", globalPropertyf("sim/custom/lights/button/absu_thro1")) 
defineProperty("absu_thro2_lamp", globalPropertyf("sim/custom/lights/button/absu_thro2")) 
defineProperty("absu_thro3_lamp", globalPropertyf("sim/custom/lights/button/absu_thro3")) 
defineProperty("stu_roll_lamp", globalPropertyf("sim/custom/lights/small/stu_roll")) 
defineProperty("stu_pitch_lamp", globalPropertyf("sim/custom/lights/small/stu_pitch")) 
defineProperty("stu_toga_lamp", globalPropertyf("sim/custom/lights/small/stu_toga")) 
defineProperty("at_1_lamp", globalPropertyf("sim/custom/lights/small/at_1")) 
defineProperty("at_2_lamp", globalPropertyf("sim/custom/lights/small/at_2")) 
defineProperty("course_lim", globalPropertyf("sim/custom/lights/course_lim")) 
defineProperty("gs_lim", globalPropertyf("sim/custom/lights/gs_lim")) 
defineProperty("wrong_trimm", globalPropertyf("sim/custom/lights/wrong_trimm")) 
defineProperty("controll_roll", globalPropertyf("sim/custom/lights/controll_roll")) 
defineProperty("controll_pitch", globalPropertyf("sim/custom/lights/controll_pitch")) 
defineProperty("yoke_sign", globalPropertyf("sim/custom/lights/yoke_sign")) 
defineProperty("triangle", globalPropertyf("sim/custom/lights/triangle")) 
defineProperty("controll_thrust", globalPropertyf("sim/custom/lights/controll_thrust")) 
defineProperty("toga", globalPropertyf("sim/custom/lights/toga")) 
defineProperty("course", globalPropertyf("sim/custom/lights/course")) 
defineProperty("glideslope", globalPropertyf("sim/custom/lights/glideslope")) 
defineProperty("zk_lamp", globalPropertyf("sim/custom/lights/zk_lamp")) 
defineProperty("thrust_automat", globalPropertyf("sim/custom/lights/thrust_automat")) 
defineProperty("stab_roll", globalPropertyf("sim/custom/lights/stab_roll")) 
defineProperty("stab_pitch", globalPropertyf("sim/custom/lights/stab_pitch")) 
defineProperty("nvu_lamp", globalPropertyf("sim/custom/lights/nvu_lamp")) 
defineProperty("vor_lamp", globalPropertyf("sim/custom/lights/vor_lamp")) 
defineProperty("stab_h", globalPropertyf("sim/custom/lights/stab_h")) 
defineProperty("stab_v", globalPropertyf("sim/custom/lights/stab_v")) 
defineProperty("stab_m", globalPropertyf("sim/custom/lights/stab_m")) 
defineProperty("pitch_control_fail", globalPropertyf("sim/custom/lights/pitch_control_fail")) 
defineProperty("roll_control_fail", globalPropertyf("sim/custom/lights/roll_control_fail")) 
defineProperty("absu_work", globalPropertyf("sim/custom/lights/absu_work")) 
defineProperty("sns_lamp", globalPropertyf("sim/custom/lights/sns_lamp")) 
defineProperty("ra56_roll_fail_1", globalPropertyf("sim/custom/lights/ra56_roll_fail_1")) 
defineProperty("ra56_roll_fail_2", globalPropertyf("sim/custom/lights/ra56_roll_fail_2")) 
defineProperty("ra56_roll_fail_3", globalPropertyf("sim/custom/lights/ra56_roll_fail_3")) 
defineProperty("ra56_pitch_fail_1", globalPropertyf("sim/custom/lights/ra56_pitch_fail_1")) 
defineProperty("ra56_pitch_fail_2", globalPropertyf("sim/custom/lights/ra56_pitch_fail_2")) 
defineProperty("ra56_pitch_fail_3", globalPropertyf("sim/custom/lights/ra56_pitch_fail_3")) 
defineProperty("ra56_course_fail_1", globalPropertyf("sim/custom/lights/ra56_course_fail_1")) 
defineProperty("ra56_course_fail_2", globalPropertyf("sim/custom/lights/ra56_course_fail_2")) 
defineProperty("ra56_course_fail_3", globalPropertyf("sim/custom/lights/ra56_course_fail_3")) 
defineProperty("eng_at_on_lamp", globalPropertyf("sim/custom/lights/engines/eng_at_on")) 
defineProperty("lamp_test", globalPropertyi("sim/custom/buttons/lamp_test_front")) 
defineProperty("day_night_set", globalPropertyf("sim/custom/lights/day_night_set")) 
defineProperty("lamp_test_eng", globalPropertyi("sim/custom/buttons/lamp_test_pa56")) 
defineProperty("roll_main_mode", globalPropertyi("sim/custom/absu/roll_main_mode")) 
defineProperty("pitch_main_mode", globalPropertyi("sim/custom/absu/pitch_main_mode")) 
defineProperty("roll_sub_mode", globalPropertyi("sim/custom/absu/roll_sub_mode")) 
defineProperty("pitch_sub_mode", globalPropertyi("sim/custom/absu/pitch_sub_mode")) 
defineProperty("stu_mode", globalPropertyi("sim/custom/absu/stu_mode")) 
defineProperty("absu_speed_off", globalPropertyi("sim/custom/switchers/console/absu_speed_off")) 
defineProperty("absu_throt_off_1", globalPropertyi("sim/custom/buttons/console/absu_throt_off_1")) 
defineProperty("absu_throt_off_2", globalPropertyi("sim/custom/buttons/console/absu_throt_off_2")) 
defineProperty("absu_throt_off_3", globalPropertyi("sim/custom/buttons/console/absu_throt_off_3")) 
defineProperty("absu_pnp_mode_1", globalPropertyi("sim/custom/absu/absu_pnp_mode_1")) 
defineProperty("absu_pnp_mode_2", globalPropertyi("sim/custom/absu/absu_pnp_mode_2")) 
defineProperty("absu_course_out", globalPropertyi("sim/custom/absu_course_out")) 
defineProperty("absu_gs_out", globalPropertyi("sim/custom/absu_gs_out")) 
defineProperty("pkp_fail_left", globalPropertyf("sim/custom/gauges/ahz/ahz_flag_L")) 
defineProperty("pkp_fail_right", globalPropertyf("sim/custom/gauges/ahz/ahz_flag_R")) 
defineProperty("mgv_contr_fail", globalPropertyf("sim/custom/gyro/mgv_contr_flag")) 
defineProperty("pressure_ind_1", globalPropertyf("sim/custom/gauges/hydro/pressure_ind_1")) 
defineProperty("pressure_ind_2", globalPropertyf("sim/custom/gauges/hydro/pressure_ind_2")) 
defineProperty("pressure_ind_3", globalPropertyf("sim/custom/gauges/hydro/pressure_ind_3")) 
defineProperty("sau_stu_on", globalPropertyi("sim/custom/switchers/ovhd/sau_stu_on"))  
defineProperty("tks_fail_left", globalPropertyi("sim/custom/tks/fail_left")) 
defineProperty("tks_fail_right", globalPropertyi("sim/custom/tks/fail_right")) 
defineProperty("elev_trimm_switcher", globalPropertyi("sim/custom/controll/elev_trimm_switcher")) 
defineProperty("emerg_elev_trimm", globalPropertyi("sim/custom/switchers/console/emerg_elev_trimm")) 
defineProperty("bus27_volt_left", globalPropertyf("sim/custom/elec/bus27_volt_left"))
defineProperty("bus27_volt_right", globalPropertyf("sim/custom/elec/bus27_volt_right"))
defineProperty("int_pitch_trim", globalPropertyf("sim/custom/trimmers/int_pitch_trim")) 
defineProperty("absu_pitch_trimm", globalPropertyi("sim/custom/absu/absu_pitch_trimm")) 
defineProperty("eng1_N1", globalPropertyf("sim/flightmodel/engine/ENGN_N1_[0]")) 
defineProperty("eng2_N1", globalPropertyf("sim/flightmodel/engine/ENGN_N1_[1]")) 
defineProperty("eng3_N1", globalPropertyf("sim/flightmodel/engine/ENGN_N1_[2]")) 
defineProperty("damp_roll_lamp", globalPropertyi("sim/custom/absu/damp_roll_lamp")) 
defineProperty("damp_pitch_lamp", globalPropertyi("sim/custom/absu/damp_pitch_lamp")) 
defineProperty("damp_yaw_lamp", globalPropertyi("sim/custom/absu/damp_yaw_lamp")) 
defineProperty("roll_contr_lamp", globalPropertyi("sim/custom/absu/roll_contr_lamp")) 
defineProperty("pitch_contr_lamp", globalPropertyi("sim/custom/absu/pitch_contr_lamp")) 
defineProperty("man_roll_lamp", globalPropertyi("sim/custom/absu/man_roll_lamp")) 
defineProperty("man_pitch_lamp", globalPropertyi("sim/custom/absu/man_pitch_lamp")) 
defineProperty("man_toga_lamp", globalPropertyi("sim/custom/absu/man_toga_lamp")) 
defineProperty("triangle_lamp_signal", globalPropertyi("sim/custom/absu/triangle_lamp_signal")) 
defineProperty("absu_ra56_roll_fail", globalPropertyi("sim/custom/failures/absu_ra56_roll_fail")) 
defineProperty("absu_ra56_pitch_fail", globalPropertyi("sim/custom/failures/absu_ra56_pitch_fail")) 
defineProperty("absu_ra56_yaw_fail", globalPropertyi("sim/custom/failures/absu_ra56_yaw_fail")) 
defineProperty("absu_at1_fail", globalPropertyi("sim/custom/failures/absu_at1_fail")) 
defineProperty("absu_at2_fail", globalPropertyi("sim/custom/failures/absu_at2_fail")) 
defineProperty("absu_damp_roll_fail", globalPropertyi("sim/custom/failures/absu_damp_roll_fail")) 
defineProperty("absu_damp_pitch_fail", globalPropertyi("sim/custom/failures/absu_damp_pitch_fail")) 
defineProperty("absu_damp_yaw_fail", globalPropertyi("sim/custom/failures/absu_damp_yaw_fail")) 
defineProperty("absu_contr_roll_fail", globalPropertyi("sim/custom/failures/absu_contr_roll_fail")) 
defineProperty("absu_contr_pitch_fail", globalPropertyi("sim/custom/failures/absu_contr_pitch_fail")) 
defineProperty("absu_calc_toga_fail", globalPropertyi("sim/custom/failures/absu_calc_toga_fail")) 
defineProperty("absu_calc_roll_fail", globalPropertyi("sim/custom/failures/absu_calc_roll_fail")) 
defineProperty("absu_calc_pitch_fail", globalPropertyi("sim/custom/failures/absu_calc_pitch_fail")) 
defineProperty("ismaster", globalPropertyf("scp/api/ismaster")) 
defineProperty("hascontrol_1", globalPropertyf("scp/api/hascontrol_1")) 
local passed = get(frame_time)
local notLoaded = true
local start_timer = 0
local function sw_reset()
	if get(eng1_N1) < 5 and get(eng2_N1) < 5 and get(eng3_N1) < 5 then
		set(absu_needles_on, 0)
		set(absu_nav_on, 0)
		set(absu_speed_prepare, 0)
		set(absu_roll_ch_on, 0)
		set(absu_pitch_ch_on, 0)
		set(hydro_ra56_rud_1, 0)
		set(hydro_ra56_rud_2, 0)
		set(hydro_ra56_rud_3, 0)
		set(hydro_ra56_ail_1, 0)
		set(hydro_ra56_ail_2, 0)
		set(hydro_ra56_ail_3, 0)
		set(hydro_ra56_elev_1, 0)
		set(hydro_ra56_elev_2, 0)
		set(hydro_ra56_elev_3, 0)
	end
	notLoaded = false
end
local switcher_sound = loadSample('Custom Sounds/metal_switch.wav')
local button_sound = loadSample('Custom Sounds/plastic_btn.wav')
local cap_sound = loadSample('Custom Sounds/cap.wav')
local button_summ_last = 0
local function buttons()
	local summ = get(absu_zk) + get(absu_reset) + get(absu_nvu) + get(absu_az1) + get(absu_az2) + get(absu_app)
	summ = summ + get(absu_gs) + get(absu_stab_m) + get(absu_stab_v) + get(absu_stab_h) + get(absu_stab)
	summ = summ + get(absu_arrest) + get(absu_speed_test_1) + get(absu_speed_test_2)
	summ = summ + get(absu_stab_speed) + get(absu_throt_off_1) + get(absu_throt_off_2) + get(absu_throt_off_3) + get(lamp_test_eng)
	if button_summ_last ~= summ then playSample(button_sound, 0) end
	button_summ_last = summ
end
local switchers_summ = 0
local function switchers()
	local summ = get(absu_zpu_sel) + get(absu_nav_on) + get(absu_landing_on) + get(absu_needles_on) + get(absu_speed_mode)
	summ = summ + get(absu_speed_change) + get(absu_speed_off) + get(absu_speed_prepare) + get(absu_speed_us_right_left)
	summ = summ + get(absu_roll_ch_on) + get(absu_pitch_ch_on) + get(absu_smooth_on)
	summ = summ + get(hydro_ra56_rud_1) + get(hydro_ra56_rud_2) + get(hydro_ra56_rud_3)
	summ = summ + get(hydro_ra56_ail_1) + get(hydro_ra56_ail_2) + get(hydro_ra56_ail_3)
	summ = summ + get(hydro_ra56_elev_1) + get(hydro_ra56_elev_2) + get(hydro_ra56_elev_3)
	summ = summ + get(hydro_circuit_auto_man) + get(hydro_long_control)
	summ = summ + get(ZK_select) + get(nav_select) + get(vbe_select)
	if switchers_summ ~= summ then playSample(switcher_sound, 0) end
	switchers_summ = summ
	local wheel = get(absu_pitch_wheel) 
	wheel = wheel + get(absu_pitch_wheel_dir) * get(frame_time) * 10
	while wheel > 20 do wheel = wheel - 20 end
	while wheel < -20 do wheel = wheel + 20 end 
	set(absu_pitch_wheel, wheel)
	if math.abs(get(absu_turn_handle)) <= 1 then set(absu_turn_handle, 0) end
end
local caps_summ = 0
local function caps()
	local summ = get(absu_arrest_cap) + get(absu_smooth_on_cap) + get(absu_speed_prepare_cap) + get(absu_speed_off_cap)
	summ = summ + get(hydro_circuit_auto_man_cap) + get(hydro_long_control_cap)
	if caps_summ ~= summ then playSample(cap_sound, 0) end
	caps_summ = summ
	if get(hydro_circuit_auto_man_cap) == 0 then set(hydro_circuit_auto_man, 0) end
	if get(hydro_long_control_cap) == 0 then set(hydro_long_control, 1) end
end
local function gauges()
	set(absu_roll_mode, get(roll_main_mode))
	set(absu_pitch_mode, get(pitch_main_mode))
end
local elev_tr_last = get(int_pitch_trim)
local stu_test_1_cntr = 0
local stu_test_2_cntr = 0
local triangle_timer = 0
local triangle_lit = 0
local function lamps()
	local test_btn = get(lamp_test) * math.max((get(bus27_volt_right) - 10) / 18.5, 0)
	local day_night = 1 - get(day_night_set) * 0.25
	local lamps_brt = math.max((math.max(get(bus27_volt_left), get(bus27_volt_right)) - 10) / 18.5, 0) * day_night
	local small_lamps_brt = math.max((math.max(get(bus27_volt_left), get(bus27_volt_right)) - 10) / 18.5, 0) 
	local roll_mode = get(roll_main_mode)
	local pitch_mode = get(pitch_main_mode)
	local roll_submode = get(roll_sub_mode)
	local pitch_submode = get(pitch_sub_mode)
	local absu_zk_lamp_brt = math.max(bool2int(roll_mode > 0 and roll_submode == 2) * lamps_brt * day_night, test_btn)
	set(absu_zk_lamp, absu_zk_lamp_brt)
	local absu_reset_lamp_brt = math.max(bool2int(roll_mode > 0 and roll_submode == 1 and pitch_submode ~= 6) * lamps_brt * day_night, test_btn) 
	set(absu_reset_lamp, absu_reset_lamp_brt)
	local absu_nvu_lamp_brt = math.max(bool2int(roll_mode > 0 and roll_submode == 3) * lamps_brt * day_night, test_btn)
	set(absu_nvu_lamp, absu_nvu_lamp_brt)
	local absu_az1_lamp_brt = math.max(bool2int(roll_mode > 0 and roll_submode == 4) * lamps_brt * day_night, test_btn)
	set(absu_az1_lamp, absu_az1_lamp_brt)
	local absu_az2_lamp_brt = math.max(bool2int(roll_mode > 0 and roll_submode == 5) * lamps_brt * day_night, test_btn)
	set(absu_az2_lamp, absu_az2_lamp_brt)
	local absu_app_lamp_brt = math.max(bool2int(roll_mode > 0 and (roll_submode == 6 or roll_submode == 10)) * lamps_brt * day_night, test_btn) 
	set(absu_app_lamp, absu_app_lamp_brt)
	local absu_gz_lamp_brt = math.max(bool2int(roll_mode > 0 and (pitch_submode == 5 or pitch_submode == 10)) * lamps_brt * day_night, test_btn) 
	set(absu_gz_lamp, absu_gz_lamp_brt)
	local absu_stab_m_lamp_brt = math.max(bool2int(pitch_mode > 0 and pitch_submode == 3) * lamps_brt * day_night, test_btn) 
	set(absu_stab_m_lamp, absu_stab_m_lamp_brt)
	local absu_stab_v_lamp_brt = math.max(bool2int(pitch_mode > 0 and pitch_submode == 2) * lamps_brt * day_night, test_btn)
	set(absu_stab_v_lamp, absu_stab_v_lamp_brt)
	local absu_stab_h_lamp_brt = math.max(bool2int(pitch_mode > 0 and pitch_submode == 4) * lamps_brt * day_night, test_btn) 
	set(absu_stab_h_lamp, absu_stab_h_lamp_brt)
	set(absu_stab_lamp, 0)
	local AT_mode = get(stu_mode)
	local absu_stab_spd_lamp_brt = math.max(bool2int(AT_mode > 2) * lamps_brt * day_night, test_btn)
	set(absu_stab_spd_lamp, absu_stab_spd_lamp_brt)
	local absu_thro1_lamp_brt = math.max(bool2int(AT_mode > 2 and get(absu_throt_off_1) == 1) * lamps_brt * day_night, test_btn)
	set(absu_thro1_lamp, absu_thro1_lamp_brt)
	local absu_thro2_lamp_brt = math.max(bool2int(AT_mode > 2 and get(absu_throt_off_2) == 1) * lamps_brt * day_night, test_btn) 
	set(absu_thro2_lamp, absu_thro2_lamp_brt)
	local absu_thro3_lamp_brt = math.max(bool2int(AT_mode > 2 and get(absu_throt_off_3) == 1) * lamps_brt * day_night, test_btn) 
	set(absu_thro3_lamp, absu_thro3_lamp_brt)
	local nav_prep = get(absu_nav_on) == 1
	local land_prep = get(absu_landing_on) == 1
	local absu_roll_mod = get(roll_main_mode)
	local absu_pitch_mod = get(pitch_main_mode)
	if get(absu_speed_test_2) == 1 and (nav_prep or land_prep) then
		stu_test_1_cntr = stu_test_1_cntr + passed
	else
		stu_test_1_cntr = 0
	end
	local stu_roll_lamp_brt = math.max(bool2int(absu_roll_mod >= 1 and absu_pitch_mod >= 1 and (land_prep) and stu_test_1_cntr < 1 and get(absu_calc_roll_fail) == 0) * lamps_brt * day_night, test_btn) 
	set(stu_roll_lamp, stu_roll_lamp_brt)
	local stu_pitch_lamp_brt = math.max(bool2int(absu_roll_mod >= 1 and absu_pitch_mod >= 1 and land_prep and stu_test_1_cntr < 0.5 and get(absu_calc_pitch_fail) == 0) * lamps_brt * day_night, test_btn) 
	set(stu_pitch_lamp, stu_pitch_lamp_brt)
	local stu_toga_lamp_brt = math.max(bool2int(absu_roll_mod >= 1 and absu_pitch_mod >= 1 and land_prep and stu_test_1_cntr < 0.5 and get(absu_calc_toga_fail) == 0) * lamps_brt * day_night, test_btn)
	set(stu_toga_lamp, stu_toga_lamp_brt)
	local at_off = get(absu_speed_off)
	if get(absu_speed_test_1) == 1 and AT_mode > 1 then
		stu_test_2_cntr = stu_test_2_cntr + passed
	else
		stu_test_2_cntr = 0
	end
	local at_1_lamp_brt = math.max(bool2int(AT_mode > 1 and at_off ~= 1 and stu_test_2_cntr < 10 and get(absu_at1_fail) == 0) * lamps_brt * day_night, test_btn)
	set(at_1_lamp, at_1_lamp_brt)
	local at_2_lamp_brt = math.max(bool2int(AT_mode > 1 and at_off ~= -1 and stu_test_2_cntr < 10 and get(absu_at2_fail) == 0) * lamps_brt * day_night, test_btn)
	set(at_2_lamp, at_2_lamp_brt)
	local elev_tr_now = get(int_pitch_trim)
	local trim_fail = bool2int(get(pitch_main_mode) == 2 and (get(elev_trimm_switcher) ~= 0 or get(emerg_elev_trimm) ~= 0) or (get(absu_pitch_trimm) ~= 0 and elev_tr_now - elev_tr_last == 0))
	elev_tr_last = elev_tr_now
	local wrong_trimm_brt = math.max(trim_fail * lamps_brt * day_night, test_btn)
	if get(ismaster) ~= 1 then
	set(wrong_trimm, wrong_trimm_brt)
	end
	local controll_roll_brt = math.max(get(man_roll_lamp) * lamps_brt * day_night, test_btn) 
	set(controll_roll, controll_roll_brt)
	local controll_pitch_brt = math.max(get(man_pitch_lamp) * lamps_brt * day_night, test_btn)
	set(controll_pitch, controll_pitch_brt)
	local yoke_sign_brt = math.max(get(man_toga_lamp) * lamps_brt * day_night, test_btn)
	set(yoke_sign, yoke_sign_brt)
	if get(triangle_lamp_signal) == 1 then
		triangle_timer = triangle_timer + passed
		if triangle_timer > 0.3 then 
			triangle_lit = 1 - triangle_lit 
			triangle_timer = 0
		end
	else
		triangle_lit = 0
		triangle_timer = 0
	end
	local triangle_brt = math.max(triangle_lit * lamps_brt * day_night, test_btn)
	set(triangle, triangle_brt)
	local controll_thrust_brt = math.max(bool2int(AT_mode == -1) * lamps_brt * day_night, test_btn)
	set(controll_thrust, controll_thrust_brt)
	local toga_brt = math.max(bool2int(pitch_mode == 2 and pitch_submode == 6) * lamps_brt * day_night, test_btn)
	set(toga, toga_brt)
	local course_lim_brt = math.max(get(absu_course_out) * lamps_brt * day_night, test_btn) 
	set(course_lim, course_lim_brt)
	local gs_lim_brt = math.max(get(absu_gs_out) * lamps_brt * day_night, test_btn)
	set(gs_lim, gs_lim_brt)
	local course_brt = math.max(bool2int(roll_mode == 2 and roll_submode == 6) * lamps_brt * day_night, test_btn)
	set(course, course_brt)
	local glideslope_brt = math.max(bool2int(pitch_mode == 2 and pitch_submode == 5) * lamps_brt * day_night, test_btn)
	set(glideslope, glideslope_brt)
	local zk_lamp_brt = math.max(bool2int(roll_mode == 2 and roll_submode == 2) * lamps_brt * day_night, test_btn)
	set(zk_lamp, zk_lamp_brt)
	local thrust_automat_brt = math.max(bool2int(AT_mode > 2) * lamps_brt * day_night, test_btn)
	set(thrust_automat, thrust_automat_brt)
	local stab_roll_brt = math.max(bool2int(roll_mode == 2 and (roll_submode == 1 or roll_submode == 10)) * lamps_brt * day_night, test_btn) 
	set(stab_roll, stab_roll_brt)
	local stab_pitch_brt = math.max(bool2int(pitch_mode == 2 and (pitch_submode == 1 or pitch_submode == 10)) * lamps_brt * day_night, test_btn)
	set(stab_pitch, stab_pitch_brt)
	local nvu_lamp_brt = math.max(bool2int(roll_mode == 2 and roll_submode == 3) * lamps_brt * day_night, test_btn)
	set(nvu_lamp, nvu_lamp_brt)
	local vor_lamp_brt = math.max(bool2int(roll_mode == 2 and (roll_submode == 4 or roll_submode == 5)) * lamps_brt * day_night, test_btn)
	set(vor_lamp, vor_lamp_brt)
	local sns_lamp_brt = math.max(bool2int(roll_mode >= 1 and roll_submode == 3 and get(nav_select) == 1) * lamps_brt * day_night, test_btn)
	set(sns_lamp, sns_lamp_brt)
	local stab_h_brt = math.max(bool2int(pitch_mode == 2 and pitch_submode == 4) * lamps_brt * day_night, test_btn)
	set(stab_h, stab_h_brt)
	local stab_v_brt = math.max(bool2int(pitch_mode == 2 and pitch_submode == 2) * lamps_brt * day_night, test_btn)
	set(stab_v, stab_v_brt)
	local stab_m_brt = math.max(bool2int(pitch_mode == 2 and pitch_submode == 3) * lamps_brt * day_night, test_btn)
	set(stab_m, stab_m_brt)
	local pitch_control_fail_brt = math.max(get(pitch_contr_lamp) * lamps_brt * day_night, test_btn)
	set(pitch_control_fail, pitch_control_fail_brt)
	local roll_control_fail_brt = math.max(get(roll_contr_lamp) * lamps_brt * day_night, test_btn) 
	set(roll_control_fail, roll_control_fail_brt)
	local absu_work_logic = get(pkp_fail_left) + get(pkp_fail_right) + get(mgv_contr_fail) < 2
	absu_work_logic = absu_work_logic and bool2int(get(pressure_ind_1) < 100) + bool2int(get(pressure_ind_2) < 100) + bool2int(get(pressure_ind_3) < 100) < 2
	local ra56_rud_on = get(hydro_ra56_rud_1) * bool2int(get(absu_ra56_yaw_fail) ~= 3) + get(hydro_ra56_rud_2) * bool2int(get(absu_ra56_yaw_fail) == 0) + get(hydro_ra56_rud_3)  * bool2int(get(absu_ra56_yaw_fail) < 2) > 1
	local ra56_ail_on = get(hydro_ra56_ail_1) * bool2int(get(absu_ra56_roll_fail) == 0) + get(hydro_ra56_ail_2) * bool2int(get(absu_ra56_roll_fail) ~= 3) + get(hydro_ra56_ail_3) * bool2int(get(absu_ra56_roll_fail) < 2) > 1
	local ra56_elev_on = get(hydro_ra56_elev_1) * bool2int(get(absu_ra56_pitch_fail) ~= 3) + get(hydro_ra56_elev_2) * bool2int(get(absu_ra56_pitch_fail) < 2) + get(hydro_ra56_elev_3) * bool2int(get(absu_ra56_pitch_fail) == 0) > 1
	local chan_1_work = get(hydro_ra56_rud_1) * bool2int(get(absu_ra56_yaw_fail) ~= 3) + get(hydro_ra56_ail_1) * bool2int(get(absu_ra56_roll_fail) == 0) + get(hydro_ra56_elev_1) * bool2int(get(absu_ra56_pitch_fail) ~= 3) > 0
	local chan_2_work = get(hydro_ra56_rud_2) * bool2int(get(absu_ra56_yaw_fail) == 0) + get(hydro_ra56_ail_2) * bool2int(get(absu_ra56_roll_fail) ~= 3) + get(hydro_ra56_elev_2) * bool2int(get(absu_ra56_pitch_fail) < 2) > 0
	local chan_3_work = get(hydro_ra56_rud_3)  * bool2int(get(absu_ra56_yaw_fail) < 2) + get(hydro_ra56_ail_3) * bool2int(get(absu_ra56_roll_fail) < 2) + get(hydro_ra56_elev_3) * bool2int(get(absu_ra56_pitch_fail) == 0) > 0
	absu_work_logic = absu_work_logic and (ra56_rud_on and ra56_ail_on and ra56_elev_on)
	absu_work_logic = absu_work_logic and chan_1_work and chan_2_work and chan_3_work
	absu_work_logic = absu_work_logic and get(sau_stu_on) == 1 and get(tks_fail_left) + get(tks_fail_right) == 0
	absu_work_logic = absu_work_logic and stu_test_1_cntr < 0.5
	absu_work_logic = absu_work_logic and get(absu_damp_roll_fail) == 0 and get(absu_damp_pitch_fail) == 0 and get(absu_damp_yaw_fail) == 0
	absu_work_logic = absu_work_logic and get(absu_contr_roll_fail) == 0 and get(absu_contr_pitch_fail) == 0
	local absu_work_brt = bool2int(absu_work_logic)
	absu_work_brt = math.max(absu_work_brt * lamps_brt * day_night, 0) 
	set(absu_work, absu_work_brt)
	local test_btn_eng = get(lamp_test_eng) * math.max(get(bus27_volt_right) - 10 / 18.5, 0)
	local ra56_roll_fail_1_brt = math.max(bool2int(get(hydro_ra56_ail_1) == 0 or get(absu_ra56_roll_fail) > 0) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_roll_fail_1, ra56_roll_fail_1_brt)
	local ra56_roll_fail_2_brt = math.max(bool2int(get(hydro_ra56_ail_2) == 0 or get(absu_ra56_roll_fail) > 2) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_roll_fail_2, ra56_roll_fail_2_brt)
	local ra56_roll_fail_3_brt = math.max(bool2int(get(hydro_ra56_ail_3) == 0 or get(absu_ra56_roll_fail) > 1) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_roll_fail_3, ra56_roll_fail_3_brt)
	local ra56_pitch_fail_1_brt = math.max(bool2int(get(hydro_ra56_elev_1) == 0 or get(absu_ra56_pitch_fail) > 2) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_pitch_fail_1, ra56_pitch_fail_1_brt)
	local ra56_pitch_fail_2_brt = math.max(bool2int(get(hydro_ra56_elev_2) == 0 or get(absu_ra56_pitch_fail) > 1) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_pitch_fail_2, ra56_pitch_fail_2_brt)
	local ra56_pitch_fail_3_brt = math.max(bool2int(get(hydro_ra56_elev_3) == 0 or get(absu_ra56_pitch_fail) > 0) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_pitch_fail_3, ra56_pitch_fail_3_brt)
	local ra56_course_fail_1_brt = math.max(bool2int(get(hydro_ra56_rud_1) == 0 or get(absu_ra56_yaw_fail) > 2) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_course_fail_1, ra56_course_fail_1_brt)
	local ra56_course_fail_2_brt = math.max(bool2int(get(hydro_ra56_rud_2) == 0 or get(absu_ra56_yaw_fail) > 0) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_course_fail_2, ra56_course_fail_2_brt)
	local ra56_course_fail_3_brt = math.max(bool2int(get(hydro_ra56_rud_3) == 0 or get(absu_ra56_yaw_fail) > 1) * lamps_brt * day_night, test_btn_eng) 
	set(ra56_course_fail_3, ra56_course_fail_3_brt)
end
function update()
	buttons()
	switchers()
	caps()
	lamps()
	gauges()
	passed = get(frame_time)
	start_timer = start_timer + passed
	if notLoaded and start_timer > 0.3 then
		sw_reset()
	end
end
