defineProperty("bus27_amp_left", globalPropertyf("sim/custom/elec/bus27_amp_left")) 
defineProperty("bus27_amp_right", globalPropertyf("sim/custom/elec/bus27_amp_right")) 
defineProperty("bus36_amp_left", globalPropertyf("sim/custom/elec/bus36_amp_left")) 
defineProperty("bus36_amp_right", globalPropertyf("sim/custom/elec/bus36_amp_right")) 
defineProperty("bus36_amp_pts250_1", globalPropertyf("sim/custom/elec/bus36_amp_pts250_1")) 
defineProperty("bus36_amp_pts250_2", globalPropertyf("sim/custom/elec/bus36_amp_pts250_2")) 
defineProperty("bus115_1_amp", globalPropertyf("sim/custom/elec/bus115_1_amp"))
defineProperty("bus115_2_amp", globalPropertyf("sim/custom/elec/bus115_2_amp"))
defineProperty("bus115_3_amp", globalPropertyf("sim/custom/elec/bus115_3_amp"))
defineProperty("bus115_em_1_amp", globalPropertyf("sim/custom/elec/bus115_em_1_amp"))
defineProperty("bus115_em_2_amp", globalPropertyf("sim/custom/elec/bus115_em_2_amp"))
defineProperty("bat_amp_cc_1", globalPropertyf("sim/custom/elec/bat_cc_1")) 
defineProperty("bat_amp_cc_2", globalPropertyf("sim/custom/elec/bat_cc_2")) 
defineProperty("bat_amp_cc_3", globalPropertyf("sim/custom/elec/bat_cc_3")) 
defineProperty("bat_amp_cc_4", globalPropertyf("sim/custom/elec/bat_cc_4")) 
defineProperty("cockpit_light_cc_left", globalPropertyf("sim/custom/elec/cockpit_light_cc_left"))
defineProperty("cockpit_light_cc_right", globalPropertyf("sim/custom/elec/cockpit_light_cc_right"))
defineProperty("ext_light_cc_left", globalPropertyf("sim/custom/elec/ext_light_cc_left"))
defineProperty("ext_light_cc_right", globalPropertyf("sim/custom/elec/ext_light_cc_right"))
defineProperty("apu_start_cc", globalPropertyf("sim/custom/elec/apu_start_cc")) 
defineProperty("fuel_pumps_27_cc", globalPropertyf("sim/custom/elec/fuel_pumps_27_cc")) 
defineProperty("ai_27_L_cc", globalPropertyf("sim/custom/antiice/ai_27_L_cc")) 
defineProperty("ai_27_R_cc", globalPropertyf("sim/custom/antiice/ai_27_R_cc")) 
defineProperty("ctr_27_L_cc", globalPropertyf("sim/custom/control/ctr_27_L_cc")) 
defineProperty("ctr_27_R_cc", globalPropertyf("sim/custom/control/ctr_27_R_cc")) 
defineProperty("msrp_27_L_cc", globalPropertyf("sim/custom/msrp/msrp_27_L_cc")) 
defineProperty("msrp_27_R_cc", globalPropertyf("sim/custom/msrp/msrp_27_R_cc")) 
defineProperty("svs27_cc", globalPropertyf("sim/custom/svs/power_27cc")) 
defineProperty("auasp_pow27_cc", globalPropertyf("sim/custom/elec/auasp_pow27_cc"))
defineProperty("rv_сс_1", globalPropertyf("sim/custom/elec/rv5_left_cc"))  
defineProperty("rv_сс_2", globalPropertyf("sim/custom/elec/rv5_right_cc"))  
defineProperty("taws_cc", globalPropertyf("sim/custom/taws/taws_cc")) 
defineProperty("fire_sys_cc", globalPropertyf("sim/custom/fire/fire_sys_cc")) 
defineProperty("vhf1_cc", globalPropertyf("sim/custom/radio/vhf1_cc"))
defineProperty("vhf2_cc", globalPropertyf("sim/custom/radio/vhf2_cc"))
defineProperty("km5_1_cc", globalPropertyf("sim/custom/tks/km5_1_cc")) 
defineProperty("km5_2_cc", globalPropertyf("sim/custom/tks/km5_1_cc")) 
defineProperty("ga_1_cc", globalPropertyf("sim/custom/tks/ga_1_cc")) 
defineProperty("ga_2_cc", globalPropertyf("sim/custom/tks/ga_2_cc")) 
defineProperty("ga_heat_cc", globalPropertyf("sim/custom/tks/ga_heat_cc")) 
defineProperty("bgmk_1_cc", globalPropertyf("sim/custom/tks/bgmk_1_cc")) 
defineProperty("bgmk_2_cc", globalPropertyf("sim/custom/tks/bgmk_2_cc")) 
defineProperty("ush_cc", globalPropertyf("sim/custom/tks/ush_cc")) 
defineProperty("agr_cc", globalPropertyf("sim/custom/ahz/agr_cc")) 
defineProperty("ark15_L_cc", globalPropertyf("sim/custom/radio/ark15_L_cc")) 
defineProperty("ark15_R_cc", globalPropertyf("sim/custom/radio/ark15_R_cc")) 
defineProperty("diss_cc", globalPropertyf("sim/custom/nvu/diss_cc")) 
defineProperty("radar_cc", globalPropertyf("sim/custom/radio/radar_cc")) 
defineProperty("rsbn_cc", globalPropertyf("sim/custom/radio/rsbn_cc")) 
defineProperty("ctr_36L_cc", globalPropertyf("sim/custom/control/ctr_36L_cc")) 
defineProperty("ctr_36R_cc", globalPropertyf("sim/custom/control/ctr_36R_cc")) 
defineProperty("svs36_cc", globalPropertyf("sim/custom/svs/power_36cc")) 
defineProperty("absu_power_cc", globalPropertyf("sim/custom/absu_power_cc")) 
defineProperty("pkp_left_power_cc", globalPropertyf("sim/custom/bkk/pkp_left_power_cc")) 
defineProperty("pkp_right_power_cc", globalPropertyf("sim/custom/bkk/pkp_right_power_cc")) 
defineProperty("mgv_ctr_power_cc", globalPropertyf("sim/custom/bkk/mgv_ctr_power_cc")) 
defineProperty("absu_at_power_cc", globalPropertyf("sim/custom/absu_at_power_cc")) 
defineProperty("nvu_cc", globalPropertyf("sim/custom/nvu/nvu_cc")) 
defineProperty("nav1_pow_cc", globalPropertyf("sim/custom/radio/nav1_pow_cc")) 
defineProperty("nav2_pow_cc", globalPropertyf("sim/custom/radio/nav2_pow_cc")) 
defineProperty("vu1_amp", globalPropertyf("sim/custom/elec/vu1_amp")) 
defineProperty("vu2_amp", globalPropertyf("sim/custom/elec/vu2_amp")) 
defineProperty("vu3_amp", globalPropertyf("sim/custom/elec/vu_res_amp")) 
defineProperty("cockpit_light_cc_115", globalPropertyf("sim/custom/elec/cockpit_light_cc_115"))
defineProperty("fuel_pumps_115_1_cc", globalPropertyf("sim/custom/elec/fuel_pumps_115_1_cc")) 
defineProperty("fuel_pumps_115_3_cc", globalPropertyf("sim/custom/elec/fuel_pumps_115_3_cc")) 
defineProperty("gs_pump_2_cc", globalPropertyf("sim/custom/hydro/gs_pump_2_cc")) 
defineProperty("gs_pump_3_cc", globalPropertyf("sim/custom/hydro/gs_pump_3_cc")) 
defineProperty("ai_115_1_cc", globalPropertyf("sim/custom/antiice/ai_115_1_cc")) 
defineProperty("ai_115_2_cc", globalPropertyf("sim/custom/antiice/ai_115_2_cc")) 
defineProperty("ai_115_3_cc", globalPropertyf("sim/custom/antiice/ai_115_3_cc")) 
defineProperty("ctr_115_1_cc", globalPropertyf("sim/custom/control/ctr_115_1_cc")) 
defineProperty("ctr_115_3_cc", globalPropertyf("sim/custom/control/ctr_115_3_cc")) 
defineProperty("svs115_cc", globalPropertyf("sim/custom/svs/power_115cc")) 
defineProperty("auasp_pow115_cc", globalPropertyf("sim/custom/elec/auasp_pow115_cc"))
defineProperty("ismaster", globalPropertyf("scp/api/ismaster")) 
defineProperty("hascontrol_1", globalPropertyf("scp/api/hascontrol_1")) 
function update()
local MASTER = get(ismaster) ~= 1	
if MASTER then	
	local bus27_L = get(bat_amp_cc_1) + get(bat_amp_cc_3) + get(cockpit_light_cc_left) + get(ext_light_cc_left) + get(fuel_pumps_27_cc) * 0.5 + get(ai_27_L_cc) + get(ctr_27_L_cc) + get(msrp_27_L_cc)
	bus27_L = bus27_L + get(svs27_cc) + get(rv_сс_1) + get(taws_cc) + get(vhf1_cc) + get(km5_1_cc) * 2 + get(ga_1_cc) * 0.5 + get(ga_2_cc) * 0.5 + get(ga_heat_cc) + get(bgmk_1_cc) + get(agr_cc)
	bus27_L = bus27_L + get(nvu_cc) * 10 + get(ark15_L_cc) + get(diss_cc) + get(rsbn_cc) * 5
	local bus27_R = get(bat_amp_cc_2) + get(bat_amp_cc_4) + get(cockpit_light_cc_right) + get(ext_light_cc_right) + get(fuel_pumps_27_cc) * 0.5 + get(ai_27_R_cc) + get(ctr_27_R_cc) + get(msrp_27_R_cc)
	bus27_R = bus27_R + get(auasp_pow27_cc) + get(rv_сс_2) + get(fire_sys_cc) + get(vhf2_cc) + get(km5_2_cc) * 2 + get(bgmk_2_cc) + get(ush_cc) + get(ark15_R_cc) + get(radar_cc) * 3
	set(bus27_amp_left, bus27_L)
	set(bus27_amp_right, bus27_R)
	local bus36_L = get(ctr_36L_cc) + get(svs36_cc) + get(absu_power_cc) * 3 + get(pkp_left_power_cc) + get(absu_at_power_cc) + get(nvu_cc) * 7 + get(ark15_L_cc) + get(diss_cc)
	local bus36_R = get(ctr_36R_cc) + get(absu_power_cc) * 3 + get(pkp_right_power_cc) + get(km5_2_cc) * 3 + get(ga_2_cc) * 2 + get(bgmk_2_cc) + get(ark15_R_cc) + get(nav2_pow_cc)
	local bus36_pts_1 = get(absu_power_cc) * 3 + get(mgv_ctr_power_cc) + get(agr_cc) + get(radar_cc)
	local bus36_pts_2 = get(km5_1_cc) * 3 + get(ga_1_cc) * 2 + get(bgmk_1_cc) + get(nav1_pow_cc)
	set(bus36_amp_left, bus36_L)
	set(bus36_amp_right, bus36_R)
	set(bus36_amp_pts250_1, bus36_pts_1)
	set(bus36_amp_pts250_2, bus36_pts_2)
	local bus115_1 = get(vu1_amp) * 0.25 + get(vu3_amp) * 0.125 + get(cockpit_light_cc_115) * 0.5 + get(fuel_pumps_115_1_cc) + get(gs_pump_2_cc) + get(ai_115_1_cc) + get(ctr_115_1_cc)
	bus115_1 = bus115_1 + get(svs115_cc) + get(rv_сс_1) + get(taws_cc) * 0.2 + get(absu_at_power_cc) + get(nvu_cc) + get(diss_cc) * 3 + get(nav1_pow_cc) * get(rsbn_cc) * 5
	local bus115_2 = get(ai_115_2_cc)
	local bus115_3 = get(vu2_amp) * 0.25 + get(vu3_amp) * 0.125 + get(cockpit_light_cc_115) * 0.5 + get(fuel_pumps_115_3_cc) + get(gs_pump_3_cc) + get(ai_115_3_cc) + get(ctr_115_3_cc)
	bus115_3 = bus115_3 + get(auasp_pow115_cc) + get(rv_сс_2) + get(absu_power_cc) + get(nav2_pow_cc) + get(radar_cc) * 3
	set(bus115_1_amp, bus115_1)
	set(bus115_2_amp, bus115_2)
	set(bus115_3_amp, bus115_3)
end
end